// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: shipping-service/v1/shipping-service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Carrier int32

const (
	Carrier_CARRIER_UNSPECIFIED Carrier = 0
	Carrier_YAMATO              Carrier = 1
	Carrier_SAGAWA              Carrier = 2
	Carrier_JAPAN_POST          Carrier = 3
	Carrier_CLICKPOST           Carrier = 4
	Carrier_NEKOPOS             Carrier = 5
)

// Enum value maps for Carrier.
var (
	Carrier_name = map[int32]string{
		0: "CARRIER_UNSPECIFIED",
		1: "YAMATO",
		2: "SAGAWA",
		3: "JAPAN_POST",
		4: "CLICKPOST",
		5: "NEKOPOS",
	}
	Carrier_value = map[string]int32{
		"CARRIER_UNSPECIFIED": 0,
		"YAMATO":              1,
		"SAGAWA":              2,
		"JAPAN_POST":          3,
		"CLICKPOST":           4,
		"NEKOPOS":             5,
	}
)

func (x Carrier) Enum() *Carrier {
	p := new(Carrier)
	*p = x
	return p
}

func (x Carrier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Carrier) Descriptor() protoreflect.EnumDescriptor {
	return file_shipping_service_v1_shipping_service_proto_enumTypes[0].Descriptor()
}

func (Carrier) Type() protoreflect.EnumType {
	return &file_shipping_service_v1_shipping_service_proto_enumTypes[0]
}

func (x Carrier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Carrier.Descriptor instead.
func (Carrier) EnumDescriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{0}
}

type ShipmentStatus int32

const (
	ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED ShipmentStatus = 0
	ShipmentStatus_PREPARING                   ShipmentStatus = 1
	ShipmentStatus_AWAITING_PICKUP             ShipmentStatus = 2
	ShipmentStatus_IN_TRANSIT                  ShipmentStatus = 3
	ShipmentStatus_AT_DISTRIBUTION_CENTER      ShipmentStatus = 4
	ShipmentStatus_OUT_FOR_DELIVERY            ShipmentStatus = 5
	ShipmentStatus_DELIVERED                   ShipmentStatus = 6
	ShipmentStatus_DELIVERY_ATTEMPTED          ShipmentStatus = 7
	ShipmentStatus_DELIVERY_FAILED             ShipmentStatus = 8
)

// Enum value maps for ShipmentStatus.
var (
	ShipmentStatus_name = map[int32]string{
		0: "SHIPMENT_STATUS_UNSPECIFIED",
		1: "PREPARING",
		2: "AWAITING_PICKUP",
		3: "IN_TRANSIT",
		4: "AT_DISTRIBUTION_CENTER",
		5: "OUT_FOR_DELIVERY",
		6: "DELIVERED",
		7: "DELIVERY_ATTEMPTED",
		8: "DELIVERY_FAILED",
	}
	ShipmentStatus_value = map[string]int32{
		"SHIPMENT_STATUS_UNSPECIFIED": 0,
		"PREPARING":                   1,
		"AWAITING_PICKUP":             2,
		"IN_TRANSIT":                  3,
		"AT_DISTRIBUTION_CENTER":      4,
		"OUT_FOR_DELIVERY":            5,
		"DELIVERED":                   6,
		"DELIVERY_ATTEMPTED":          7,
		"DELIVERY_FAILED":             8,
	}
)

func (x ShipmentStatus) Enum() *ShipmentStatus {
	p := new(ShipmentStatus)
	*p = x
	return p
}

func (x ShipmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShipmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shipping_service_v1_shipping_service_proto_enumTypes[1].Descriptor()
}

func (ShipmentStatus) Type() protoreflect.EnumType {
	return &file_shipping_service_v1_shipping_service_proto_enumTypes[1]
}

func (x ShipmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShipmentStatus.Descriptor instead.
func (ShipmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{1}
}

type TimeSlot int32

const (
	TimeSlot_TIME_SLOT_UNSPECIFIED TimeSlot = 0
	TimeSlot_MORNING               TimeSlot = 1
	TimeSlot_NOON_TO_2PM           TimeSlot = 2
	TimeSlot_PM_2_TO_4             TimeSlot = 3
	TimeSlot_PM_4_TO_6             TimeSlot = 4
	TimeSlot_PM_6_TO_8             TimeSlot = 5
	TimeSlot_PM_7_TO_9             TimeSlot = 6
)

// Enum value maps for TimeSlot.
var (
	TimeSlot_name = map[int32]string{
		0: "TIME_SLOT_UNSPECIFIED",
		1: "MORNING",
		2: "NOON_TO_2PM",
		3: "PM_2_TO_4",
		4: "PM_4_TO_6",
		5: "PM_6_TO_8",
		6: "PM_7_TO_9",
	}
	TimeSlot_value = map[string]int32{
		"TIME_SLOT_UNSPECIFIED": 0,
		"MORNING":               1,
		"NOON_TO_2PM":           2,
		"PM_2_TO_4":             3,
		"PM_4_TO_6":             4,
		"PM_6_TO_8":             5,
		"PM_7_TO_9":             6,
	}
)

func (x TimeSlot) Enum() *TimeSlot {
	p := new(TimeSlot)
	*p = x
	return p
}

func (x TimeSlot) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeSlot) Descriptor() protoreflect.EnumDescriptor {
	return file_shipping_service_v1_shipping_service_proto_enumTypes[2].Descriptor()
}

func (TimeSlot) Type() protoreflect.EnumType {
	return &file_shipping_service_v1_shipping_service_proto_enumTypes[2]
}

func (x TimeSlot) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeSlot.Descriptor instead.
func (TimeSlot) EnumDescriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{2}
}

type DeliveryOption int32

const (
	DeliveryOption_DELIVERY_OPTION_UNSPECIFIED DeliveryOption = 0
	DeliveryOption_STANDARD                    DeliveryOption = 1
	DeliveryOption_FRONT_DOOR                  DeliveryOption = 2
	DeliveryOption_DELIVERY_BOX                DeliveryOption = 3
	DeliveryOption_GAS_METER_BOX               DeliveryOption = 4
	DeliveryOption_GIFT_WRAPPING               DeliveryOption = 5
)

// Enum value maps for DeliveryOption.
var (
	DeliveryOption_name = map[int32]string{
		0: "DELIVERY_OPTION_UNSPECIFIED",
		1: "STANDARD",
		2: "FRONT_DOOR",
		3: "DELIVERY_BOX",
		4: "GAS_METER_BOX",
		5: "GIFT_WRAPPING",
	}
	DeliveryOption_value = map[string]int32{
		"DELIVERY_OPTION_UNSPECIFIED": 0,
		"STANDARD":                    1,
		"FRONT_DOOR":                  2,
		"DELIVERY_BOX":                3,
		"GAS_METER_BOX":               4,
		"GIFT_WRAPPING":               5,
	}
)

func (x DeliveryOption) Enum() *DeliveryOption {
	p := new(DeliveryOption)
	*p = x
	return p
}

func (x DeliveryOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryOption) Descriptor() protoreflect.EnumDescriptor {
	return file_shipping_service_v1_shipping_service_proto_enumTypes[3].Descriptor()
}

func (DeliveryOption) Type() protoreflect.EnumType {
	return &file_shipping_service_v1_shipping_service_proto_enumTypes[3]
}

func (x DeliveryOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryOption.Descriptor instead.
func (DeliveryOption) EnumDescriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{3}
}

type ShippingMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Carrier       Carrier                `protobuf:"varint,4,opt,name=carrier,proto3,enum=shipping_service.v1.Carrier" json:"carrier,omitempty"`
	BaseFee       string                 `protobuf:"bytes,5,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`
	WeightLimitKg string                 `protobuf:"bytes,6,opt,name=weight_limit_kg,json=weightLimitKg,proto3" json:"weight_limit_kg,omitempty"`
	SizeLimitCm   int32                  `protobuf:"varint,7,opt,name=size_limit_cm,json=sizeLimitCm,proto3" json:"size_limit_cm,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingMethod) Reset() {
	*x = ShippingMethod{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingMethod) ProtoMessage() {}

func (x *ShippingMethod) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingMethod.ProtoReflect.Descriptor instead.
func (*ShippingMethod) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{0}
}

func (x *ShippingMethod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShippingMethod) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *ShippingMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShippingMethod) GetCarrier() Carrier {
	if x != nil {
		return x.Carrier
	}
	return Carrier_CARRIER_UNSPECIFIED
}

func (x *ShippingMethod) GetBaseFee() string {
	if x != nil {
		return x.BaseFee
	}
	return ""
}

func (x *ShippingMethod) GetWeightLimitKg() string {
	if x != nil {
		return x.WeightLimitKg
	}
	return ""
}

func (x *ShippingMethod) GetSizeLimitCm() int32 {
	if x != nil {
		return x.SizeLimitCm
	}
	return 0
}

func (x *ShippingMethod) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ShippingMethod) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ShippingMethod) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ShippingRate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShippingMethodId string                 `protobuf:"bytes,2,opt,name=shipping_method_id,json=shippingMethodId,proto3" json:"shipping_method_id,omitempty"`
	Prefecture       string                 `protobuf:"bytes,3,opt,name=prefecture,proto3" json:"prefecture,omitempty"`
	BaseRate         string                 `protobuf:"bytes,4,opt,name=base_rate,json=baseRate,proto3" json:"base_rate,omitempty"`
	WeightRatePerKg  string                 `protobuf:"bytes,5,opt,name=weight_rate_per_kg,json=weightRatePerKg,proto3" json:"weight_rate_per_kg,omitempty"`
	SizeRatePerCm    string                 `protobuf:"bytes,6,opt,name=size_rate_per_cm,json=sizeRatePerCm,proto3" json:"size_rate_per_cm,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ShippingRate) Reset() {
	*x = ShippingRate{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingRate) ProtoMessage() {}

func (x *ShippingRate) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingRate.ProtoReflect.Descriptor instead.
func (*ShippingRate) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{1}
}

func (x *ShippingRate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShippingRate) GetShippingMethodId() string {
	if x != nil {
		return x.ShippingMethodId
	}
	return ""
}

func (x *ShippingRate) GetPrefecture() string {
	if x != nil {
		return x.Prefecture
	}
	return ""
}

func (x *ShippingRate) GetBaseRate() string {
	if x != nil {
		return x.BaseRate
	}
	return ""
}

func (x *ShippingRate) GetWeightRatePerKg() string {
	if x != nil {
		return x.WeightRatePerKg
	}
	return ""
}

func (x *ShippingRate) GetSizeRatePerCm() string {
	if x != nil {
		return x.SizeRatePerCm
	}
	return ""
}

func (x *ShippingRate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Shipment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId          string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TrackingNumber   string                 `protobuf:"bytes,3,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Carrier          Carrier                `protobuf:"varint,4,opt,name=carrier,proto3,enum=shipping_service.v1.Carrier" json:"carrier,omitempty"`
	Status           ShipmentStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=shipping_service.v1.ShipmentStatus" json:"status,omitempty"`
	ShippingAddress  string                 `protobuf:"bytes,6,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	RecipientName    string                 `protobuf:"bytes,7,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	RecipientPhone   string                 `protobuf:"bytes,8,opt,name=recipient_phone,json=recipientPhone,proto3" json:"recipient_phone,omitempty"`
	DeliveryDate     string                 `protobuf:"bytes,9,opt,name=delivery_date,json=deliveryDate,proto3" json:"delivery_date,omitempty"` // YYYY-MM-DD format
	DeliveryTimeSlot TimeSlot               `protobuf:"varint,10,opt,name=delivery_time_slot,json=deliveryTimeSlot,proto3,enum=shipping_service.v1.TimeSlot" json:"delivery_time_slot,omitempty"`
	DeliveryOption   DeliveryOption         `protobuf:"varint,11,opt,name=delivery_option,json=deliveryOption,proto3,enum=shipping_service.v1.DeliveryOption" json:"delivery_option,omitempty"`
	ShippingFee      string                 `protobuf:"bytes,12,opt,name=shipping_fee,json=shippingFee,proto3" json:"shipping_fee,omitempty"`
	DispatchedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=dispatched_at,json=dispatchedAt,proto3" json:"dispatched_at,omitempty"`
	DeliveredAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{2}
}

func (x *Shipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shipment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Shipment) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *Shipment) GetCarrier() Carrier {
	if x != nil {
		return x.Carrier
	}
	return Carrier_CARRIER_UNSPECIFIED
}

func (x *Shipment) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *Shipment) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

func (x *Shipment) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *Shipment) GetRecipientPhone() string {
	if x != nil {
		return x.RecipientPhone
	}
	return ""
}

func (x *Shipment) GetDeliveryDate() string {
	if x != nil {
		return x.DeliveryDate
	}
	return ""
}

func (x *Shipment) GetDeliveryTimeSlot() TimeSlot {
	if x != nil {
		return x.DeliveryTimeSlot
	}
	return TimeSlot_TIME_SLOT_UNSPECIFIED
}

func (x *Shipment) GetDeliveryOption() DeliveryOption {
	if x != nil {
		return x.DeliveryOption
	}
	return DeliveryOption_DELIVERY_OPTION_UNSPECIFIED
}

func (x *Shipment) GetShippingFee() string {
	if x != nil {
		return x.ShippingFee
	}
	return ""
}

func (x *Shipment) GetDispatchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DispatchedAt
	}
	return nil
}

func (x *Shipment) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *Shipment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Shipment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ShipmentHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShipmentId    string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	OldStatus     ShipmentStatus         `protobuf:"varint,3,opt,name=old_status,json=oldStatus,proto3,enum=shipping_service.v1.ShipmentStatus" json:"old_status,omitempty"`
	NewStatus     ShipmentStatus         `protobuf:"varint,4,opt,name=new_status,json=newStatus,proto3,enum=shipping_service.v1.ShipmentStatus" json:"new_status,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentHistory) Reset() {
	*x = ShipmentHistory{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentHistory) ProtoMessage() {}

func (x *ShipmentHistory) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentHistory.ProtoReflect.Descriptor instead.
func (*ShipmentHistory) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{3}
}

func (x *ShipmentHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShipmentHistory) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *ShipmentHistory) GetOldStatus() ShipmentStatus {
	if x != nil {
		return x.OldStatus
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *ShipmentHistory) GetNewStatus() ShipmentStatus {
	if x != nil {
		return x.NewStatus
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *ShipmentHistory) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ShipmentHistory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShipmentHistory) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *ShipmentHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CarrierTracking struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShipmentId     string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,3,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Carrier        Carrier                `protobuf:"varint,4,opt,name=carrier,proto3,enum=shipping_service.v1.Carrier" json:"carrier,omitempty"`
	LastUpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	TrackingData   string                 `protobuf:"bytes,6,opt,name=tracking_data,json=trackingData,proto3" json:"tracking_data,omitempty"` // JSON format
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CarrierTracking) Reset() {
	*x = CarrierTracking{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarrierTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarrierTracking) ProtoMessage() {}

func (x *CarrierTracking) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarrierTracking.ProtoReflect.Descriptor instead.
func (*CarrierTracking) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{4}
}

func (x *CarrierTracking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CarrierTracking) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *CarrierTracking) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *CarrierTracking) GetCarrier() Carrier {
	if x != nil {
		return x.Carrier
	}
	return Carrier_CARRIER_UNSPECIFIED
}

func (x *CarrierTracking) GetLastUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdatedAt
	}
	return nil
}

func (x *CarrierTracking) GetTrackingData() string {
	if x != nil {
		return x.TrackingData
	}
	return ""
}

func (x *CarrierTracking) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CarrierTracking) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CalculateShippingFeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Prefecture    string                 `protobuf:"bytes,2,opt,name=prefecture,proto3" json:"prefecture,omitempty"`
	TotalWeightKg string                 `protobuf:"bytes,3,opt,name=total_weight_kg,json=totalWeightKg,proto3" json:"total_weight_kg,omitempty"`
	TotalSizeCm   int32                  `protobuf:"varint,4,opt,name=total_size_cm,json=totalSizeCm,proto3" json:"total_size_cm,omitempty"`
	Subtotal      string                 `protobuf:"bytes,5,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateShippingFeeRequest) Reset() {
	*x = CalculateShippingFeeRequest{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateShippingFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateShippingFeeRequest) ProtoMessage() {}

func (x *CalculateShippingFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateShippingFeeRequest.ProtoReflect.Descriptor instead.
func (*CalculateShippingFeeRequest) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{5}
}

func (x *CalculateShippingFeeRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *CalculateShippingFeeRequest) GetPrefecture() string {
	if x != nil {
		return x.Prefecture
	}
	return ""
}

func (x *CalculateShippingFeeRequest) GetTotalWeightKg() string {
	if x != nil {
		return x.TotalWeightKg
	}
	return ""
}

func (x *CalculateShippingFeeRequest) GetTotalSizeCm() int32 {
	if x != nil {
		return x.TotalSizeCm
	}
	return 0
}

func (x *CalculateShippingFeeRequest) GetSubtotal() string {
	if x != nil {
		return x.Subtotal
	}
	return ""
}

type CreateShipmentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ShippingMethodId string                 `protobuf:"bytes,2,opt,name=shipping_method_id,json=shippingMethodId,proto3" json:"shipping_method_id,omitempty"`
	ShippingAddress  string                 `protobuf:"bytes,3,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	RecipientName    string                 `protobuf:"bytes,4,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	RecipientPhone   string                 `protobuf:"bytes,5,opt,name=recipient_phone,json=recipientPhone,proto3" json:"recipient_phone,omitempty"`
	DeliveryDate     string                 `protobuf:"bytes,6,opt,name=delivery_date,json=deliveryDate,proto3" json:"delivery_date,omitempty"` // YYYY-MM-DD format
	DeliveryTimeSlot TimeSlot               `protobuf:"varint,7,opt,name=delivery_time_slot,json=deliveryTimeSlot,proto3,enum=shipping_service.v1.TimeSlot" json:"delivery_time_slot,omitempty"`
	DeliveryOption   DeliveryOption         `protobuf:"varint,8,opt,name=delivery_option,json=deliveryOption,proto3,enum=shipping_service.v1.DeliveryOption" json:"delivery_option,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateShipmentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateShipmentRequest) GetShippingMethodId() string {
	if x != nil {
		return x.ShippingMethodId
	}
	return ""
}

func (x *CreateShipmentRequest) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

func (x *CreateShipmentRequest) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *CreateShipmentRequest) GetRecipientPhone() string {
	if x != nil {
		return x.RecipientPhone
	}
	return ""
}

func (x *CreateShipmentRequest) GetDeliveryDate() string {
	if x != nil {
		return x.DeliveryDate
	}
	return ""
}

func (x *CreateShipmentRequest) GetDeliveryTimeSlot() TimeSlot {
	if x != nil {
		return x.DeliveryTimeSlot
	}
	return TimeSlot_TIME_SLOT_UNSPECIFIED
}

func (x *CreateShipmentRequest) GetDeliveryOption() DeliveryOption {
	if x != nil {
		return x.DeliveryOption
	}
	return DeliveryOption_DELIVERY_OPTION_UNSPECIFIED
}

type RegisterTrackingNumberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId     string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,2,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Carrier        Carrier                `protobuf:"varint,3,opt,name=carrier,proto3,enum=shipping_service.v1.Carrier" json:"carrier,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterTrackingNumberRequest) Reset() {
	*x = RegisterTrackingNumberRequest{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTrackingNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTrackingNumberRequest) ProtoMessage() {}

func (x *RegisterTrackingNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTrackingNumberRequest.ProtoReflect.Descriptor instead.
func (*RegisterTrackingNumberRequest) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterTrackingNumberRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *RegisterTrackingNumberRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *RegisterTrackingNumberRequest) GetCarrier() Carrier {
	if x != nil {
		return x.Carrier
	}
	return Carrier_CARRIER_UNSPECIFIED
}

type UpdateShipmentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	NewStatus     ShipmentStatus         `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=shipping_service.v1.ShipmentStatus" json:"new_status,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShipmentStatusRequest) Reset() {
	*x = UpdateShipmentStatusRequest{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShipmentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShipmentStatusRequest) ProtoMessage() {}

func (x *UpdateShipmentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShipmentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateShipmentStatusRequest) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateShipmentStatusRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *UpdateShipmentStatusRequest) GetNewStatus() ShipmentStatus {
	if x != nil {
		return x.NewStatus
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *UpdateShipmentStatusRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateShipmentStatusRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateShipmentStatusRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type GetShipmentDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentDetailRequest) Reset() {
	*x = GetShipmentDetailRequest{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentDetailRequest) ProtoMessage() {}

func (x *GetShipmentDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentDetailRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentDetailRequest) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetShipmentDetailRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type GetShipmentByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentByOrderRequest) Reset() {
	*x = GetShipmentByOrderRequest{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentByOrderRequest) ProtoMessage() {}

func (x *GetShipmentByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentByOrderRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentByOrderRequest) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetShipmentByOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type SyncCarrierTrackingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCarrierTrackingRequest) Reset() {
	*x = SyncCarrierTrackingRequest{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCarrierTrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCarrierTrackingRequest) ProtoMessage() {}

func (x *SyncCarrierTrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCarrierTrackingRequest.ProtoReflect.Descriptor instead.
func (*SyncCarrierTrackingRequest) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{11}
}

func (x *SyncCarrierTrackingRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type BatchSyncAllShipmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSyncAllShipmentsRequest) Reset() {
	*x = BatchSyncAllShipmentsRequest{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSyncAllShipmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSyncAllShipmentsRequest) ProtoMessage() {}

func (x *BatchSyncAllShipmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSyncAllShipmentsRequest.ProtoReflect.Descriptor instead.
func (*BatchSyncAllShipmentsRequest) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{12}
}

type BatchSyncAllShipmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSynced   int32                  `protobuf:"varint,1,opt,name=total_synced,json=totalSynced,proto3" json:"total_synced,omitempty"`
	TotalUpdated  int32                  `protobuf:"varint,2,opt,name=total_updated,json=totalUpdated,proto3" json:"total_updated,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSyncAllShipmentsResponse) Reset() {
	*x = BatchSyncAllShipmentsResponse{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSyncAllShipmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSyncAllShipmentsResponse) ProtoMessage() {}

func (x *BatchSyncAllShipmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSyncAllShipmentsResponse.ProtoReflect.Descriptor instead.
func (*BatchSyncAllShipmentsResponse) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{13}
}

func (x *BatchSyncAllShipmentsResponse) GetTotalSynced() int32 {
	if x != nil {
		return x.TotalSynced
	}
	return 0
}

func (x *BatchSyncAllShipmentsResponse) GetTotalUpdated() int32 {
	if x != nil {
		return x.TotalUpdated
	}
	return 0
}

func (x *BatchSyncAllShipmentsResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ValidateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostalCode    string                 `protobuf:"bytes,1,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Prefecture    string                 `protobuf:"bytes,2,opt,name=prefecture,proto3" json:"prefecture,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	AddressLine   string                 `protobuf:"bytes,4,opt,name=address_line,json=addressLine,proto3" json:"address_line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAddressRequest) Reset() {
	*x = ValidateAddressRequest{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAddressRequest) ProtoMessage() {}

func (x *ValidateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAddressRequest.ProtoReflect.Descriptor instead.
func (*ValidateAddressRequest) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{14}
}

func (x *ValidateAddressRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *ValidateAddressRequest) GetPrefecture() string {
	if x != nil {
		return x.Prefecture
	}
	return ""
}

func (x *ValidateAddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ValidateAddressRequest) GetAddressLine() string {
	if x != nil {
		return x.AddressLine
	}
	return ""
}

type NormalizeAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostalCode    string                 `protobuf:"bytes,1,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Prefecture    string                 `protobuf:"bytes,2,opt,name=prefecture,proto3" json:"prefecture,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	AddressLine   string                 `protobuf:"bytes,4,opt,name=address_line,json=addressLine,proto3" json:"address_line,omitempty"`
	Building      string                 `protobuf:"bytes,5,opt,name=building,proto3" json:"building,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizeAddressRequest) Reset() {
	*x = NormalizeAddressRequest{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizeAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeAddressRequest) ProtoMessage() {}

func (x *NormalizeAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizeAddressRequest.ProtoReflect.Descriptor instead.
func (*NormalizeAddressRequest) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{15}
}

func (x *NormalizeAddressRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *NormalizeAddressRequest) GetPrefecture() string {
	if x != nil {
		return x.Prefecture
	}
	return ""
}

func (x *NormalizeAddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *NormalizeAddressRequest) GetAddressLine() string {
	if x != nil {
		return x.AddressLine
	}
	return ""
}

func (x *NormalizeAddressRequest) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

type CalculateShippingFeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateShippingFeeResponse) Reset() {
	*x = CalculateShippingFeeResponse{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateShippingFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateShippingFeeResponse) ProtoMessage() {}

func (x *CalculateShippingFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateShippingFeeResponse.ProtoReflect.Descriptor instead.
func (*CalculateShippingFeeResponse) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{16}
}

func (x *CalculateShippingFeeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CalculateShippingFeeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{17}
}

func (x *CreateShipmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateShipmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterTrackingNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTrackingNumberResponse) Reset() {
	*x = RegisterTrackingNumberResponse{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTrackingNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTrackingNumberResponse) ProtoMessage() {}

func (x *RegisterTrackingNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTrackingNumberResponse.ProtoReflect.Descriptor instead.
func (*RegisterTrackingNumberResponse) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{18}
}

func (x *RegisterTrackingNumberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterTrackingNumberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateShipmentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShipmentStatusResponse) Reset() {
	*x = UpdateShipmentStatusResponse{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShipmentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShipmentStatusResponse) ProtoMessage() {}

func (x *UpdateShipmentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShipmentStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateShipmentStatusResponse) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateShipmentStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateShipmentStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetShipmentDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentDetailResponse) Reset() {
	*x = GetShipmentDetailResponse{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentDetailResponse) ProtoMessage() {}

func (x *GetShipmentDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentDetailResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentDetailResponse) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetShipmentDetailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetShipmentDetailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetShipmentByOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentByOrderResponse) Reset() {
	*x = GetShipmentByOrderResponse{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentByOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentByOrderResponse) ProtoMessage() {}

func (x *GetShipmentByOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentByOrderResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentByOrderResponse) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetShipmentByOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetShipmentByOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SyncCarrierTrackingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCarrierTrackingResponse) Reset() {
	*x = SyncCarrierTrackingResponse{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCarrierTrackingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCarrierTrackingResponse) ProtoMessage() {}

func (x *SyncCarrierTrackingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCarrierTrackingResponse.ProtoReflect.Descriptor instead.
func (*SyncCarrierTrackingResponse) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{22}
}

func (x *SyncCarrierTrackingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncCarrierTrackingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAddressResponse) Reset() {
	*x = ValidateAddressResponse{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAddressResponse) ProtoMessage() {}

func (x *ValidateAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAddressResponse.ProtoReflect.Descriptor instead.
func (*ValidateAddressResponse) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{23}
}

func (x *ValidateAddressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ValidateAddressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NormalizeAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizeAddressResponse) Reset() {
	*x = NormalizeAddressResponse{}
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizeAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeAddressResponse) ProtoMessage() {}

func (x *NormalizeAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizeAddressResponse.ProtoReflect.Descriptor instead.
func (*NormalizeAddressResponse) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_service_proto_rawDescGZIP(), []int{24}
}

func (x *NormalizeAddressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NormalizeAddressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_shipping_service_v1_shipping_service_proto protoreflect.FileDescriptor

const file_shipping_service_v1_shipping_service_proto_rawDesc = "" +
	"\n" +
	"*shipping-service/v1/shipping-service.proto\x12\x13shipping_service.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xff\x02\n" +
	"\x0eShippingMethod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x126\n" +
	"\acarrier\x18\x04 \x01(\x0e2\x1c.shipping_service.v1.CarrierR\acarrier\x12\x19\n" +
	"\bbase_fee\x18\x05 \x01(\tR\abaseFee\x12&\n" +
	"\x0fweight_limit_kg\x18\x06 \x01(\tR\rweightLimitKg\x12\"\n" +
	"\rsize_limit_cm\x18\a \x01(\x05R\vsizeLimitCm\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9a\x02\n" +
	"\fShippingRate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12shipping_method_id\x18\x02 \x01(\tR\x10shippingMethodId\x12\x1e\n" +
	"\n" +
	"prefecture\x18\x03 \x01(\tR\n" +
	"prefecture\x12\x1b\n" +
	"\tbase_rate\x18\x04 \x01(\tR\bbaseRate\x12+\n" +
	"\x12weight_rate_per_kg\x18\x05 \x01(\tR\x0fweightRatePerKg\x12'\n" +
	"\x10size_rate_per_cm\x18\x06 \x01(\tR\rsizeRatePerCm\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa7\x06\n" +
	"\bShipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12'\n" +
	"\x0ftracking_number\x18\x03 \x01(\tR\x0etrackingNumber\x126\n" +
	"\acarrier\x18\x04 \x01(\x0e2\x1c.shipping_service.v1.CarrierR\acarrier\x12;\n" +
	"\x06status\x18\x05 \x01(\x0e2#.shipping_service.v1.ShipmentStatusR\x06status\x12)\n" +
	"\x10shipping_address\x18\x06 \x01(\tR\x0fshippingAddress\x12%\n" +
	"\x0erecipient_name\x18\a \x01(\tR\rrecipientName\x12'\n" +
	"\x0frecipient_phone\x18\b \x01(\tR\x0erecipientPhone\x12#\n" +
	"\rdelivery_date\x18\t \x01(\tR\fdeliveryDate\x12K\n" +
	"\x12delivery_time_slot\x18\n" +
	" \x01(\x0e2\x1d.shipping_service.v1.TimeSlotR\x10deliveryTimeSlot\x12L\n" +
	"\x0fdelivery_option\x18\v \x01(\x0e2#.shipping_service.v1.DeliveryOptionR\x0edeliveryOption\x12!\n" +
	"\fshipping_fee\x18\f \x01(\tR\vshippingFee\x12?\n" +
	"\rdispatched_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\fdispatchedAt\x12=\n" +
	"\fdelivered_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe2\x02\n" +
	"\x0fShipmentHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\x12B\n" +
	"\n" +
	"old_status\x18\x03 \x01(\x0e2#.shipping_service.v1.ShipmentStatusR\toldStatus\x12B\n" +
	"\n" +
	"new_status\x18\x04 \x01(\x0e2#.shipping_service.v1.ShipmentStatusR\tnewStatus\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"updated_by\x18\a \x01(\tR\tupdatedBy\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x82\x03\n" +
	"\x0fCarrierTracking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\x12'\n" +
	"\x0ftracking_number\x18\x03 \x01(\tR\x0etrackingNumber\x126\n" +
	"\acarrier\x18\x04 \x01(\x0e2\x1c.shipping_service.v1.CarrierR\acarrier\x12B\n" +
	"\x0flast_updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rlastUpdatedAt\x12#\n" +
	"\rtracking_data\x18\x06 \x01(\tR\ftrackingData\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbe\x01\n" +
	"\x1bCalculateShippingFeeRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12\x1e\n" +
	"\n" +
	"prefecture\x18\x02 \x01(\tR\n" +
	"prefecture\x12&\n" +
	"\x0ftotal_weight_kg\x18\x03 \x01(\tR\rtotalWeightKg\x12\"\n" +
	"\rtotal_size_cm\x18\x04 \x01(\x05R\vtotalSizeCm\x12\x1a\n" +
	"\bsubtotal\x18\x05 \x01(\tR\bsubtotal\"\x9b\x03\n" +
	"\x15CreateShipmentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12,\n" +
	"\x12shipping_method_id\x18\x02 \x01(\tR\x10shippingMethodId\x12)\n" +
	"\x10shipping_address\x18\x03 \x01(\tR\x0fshippingAddress\x12%\n" +
	"\x0erecipient_name\x18\x04 \x01(\tR\rrecipientName\x12'\n" +
	"\x0frecipient_phone\x18\x05 \x01(\tR\x0erecipientPhone\x12#\n" +
	"\rdelivery_date\x18\x06 \x01(\tR\fdeliveryDate\x12K\n" +
	"\x12delivery_time_slot\x18\a \x01(\x0e2\x1d.shipping_service.v1.TimeSlotR\x10deliveryTimeSlot\x12L\n" +
	"\x0fdelivery_option\x18\b \x01(\x0e2#.shipping_service.v1.DeliveryOptionR\x0edeliveryOption\"\xa1\x01\n" +
	"\x1dRegisterTrackingNumberRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12'\n" +
	"\x0ftracking_number\x18\x02 \x01(\tR\x0etrackingNumber\x126\n" +
	"\acarrier\x18\x03 \x01(\x0e2\x1c.shipping_service.v1.CarrierR\acarrier\"\xdf\x01\n" +
	"\x1bUpdateShipmentStatusRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12B\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2#.shipping_service.v1.ShipmentStatusR\tnewStatus\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x05 \x01(\tR\tupdatedBy\";\n" +
	"\x18GetShipmentDetailRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\"6\n" +
	"\x19GetShipmentByOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"=\n" +
	"\x1aSyncCarrierTrackingRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\"\x1e\n" +
	"\x1cBatchSyncAllShipmentsRequest\"\x7f\n" +
	"\x1dBatchSyncAllShipmentsResponse\x12!\n" +
	"\ftotal_synced\x18\x01 \x01(\x05R\vtotalSynced\x12#\n" +
	"\rtotal_updated\x18\x02 \x01(\x05R\ftotalUpdated\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"\x90\x01\n" +
	"\x16ValidateAddressRequest\x12\x1f\n" +
	"\vpostal_code\x18\x01 \x01(\tR\n" +
	"postalCode\x12\x1e\n" +
	"\n" +
	"prefecture\x18\x02 \x01(\tR\n" +
	"prefecture\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12!\n" +
	"\faddress_line\x18\x04 \x01(\tR\vaddressLine\"\xad\x01\n" +
	"\x17NormalizeAddressRequest\x12\x1f\n" +
	"\vpostal_code\x18\x01 \x01(\tR\n" +
	"postalCode\x12\x1e\n" +
	"\n" +
	"prefecture\x18\x02 \x01(\tR\n" +
	"prefecture\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12!\n" +
	"\faddress_line\x18\x04 \x01(\tR\vaddressLine\x12\x1a\n" +
	"\bbuilding\x18\x05 \x01(\tR\bbuilding\"R\n" +
	"\x1cCalculateShippingFeeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x16CreateShipmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"T\n" +
	"\x1eRegisterTrackingNumberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"R\n" +
	"\x1cUpdateShipmentStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x19GetShipmentDetailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"P\n" +
	"\x1aGetShipmentByOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Q\n" +
	"\x1bSyncCarrierTrackingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x17ValidateAddressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\x18NormalizeAddressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*f\n" +
	"\aCarrier\x12\x17\n" +
	"\x13CARRIER_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06YAMATO\x10\x01\x12\n" +
	"\n" +
	"\x06SAGAWA\x10\x02\x12\x0e\n" +
	"\n" +
	"JAPAN_POST\x10\x03\x12\r\n" +
	"\tCLICKPOST\x10\x04\x12\v\n" +
	"\aNEKOPOS\x10\x05*\xd3\x01\n" +
	"\x0eShipmentStatus\x12\x1f\n" +
	"\x1bSHIPMENT_STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tPREPARING\x10\x01\x12\x13\n" +
	"\x0fAWAITING_PICKUP\x10\x02\x12\x0e\n" +
	"\n" +
	"IN_TRANSIT\x10\x03\x12\x1a\n" +
	"\x16AT_DISTRIBUTION_CENTER\x10\x04\x12\x14\n" +
	"\x10OUT_FOR_DELIVERY\x10\x05\x12\r\n" +
	"\tDELIVERED\x10\x06\x12\x16\n" +
	"\x12DELIVERY_ATTEMPTED\x10\a\x12\x13\n" +
	"\x0fDELIVERY_FAILED\x10\b*\x7f\n" +
	"\bTimeSlot\x12\x19\n" +
	"\x15TIME_SLOT_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aMORNING\x10\x01\x12\x0f\n" +
	"\vNOON_TO_2PM\x10\x02\x12\r\n" +
	"\tPM_2_TO_4\x10\x03\x12\r\n" +
	"\tPM_4_TO_6\x10\x04\x12\r\n" +
	"\tPM_6_TO_8\x10\x05\x12\r\n" +
	"\tPM_7_TO_9\x10\x06*\x87\x01\n" +
	"\x0eDeliveryOption\x12\x1f\n" +
	"\x1bDELIVERY_OPTION_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSTANDARD\x10\x01\x12\x0e\n" +
	"\n" +
	"FRONT_DOOR\x10\x02\x12\x10\n" +
	"\fDELIVERY_BOX\x10\x03\x12\x11\n" +
	"\rGAS_METER_BOX\x10\x04\x12\x11\n" +
	"\rGIFT_WRAPPING\x10\x052\xbe\b\n" +
	"\x0fShippingService\x12{\n" +
	"\x14CalculateShippingFee\x120.shipping_service.v1.CalculateShippingFeeRequest\x1a1.shipping_service.v1.CalculateShippingFeeResponse\x12i\n" +
	"\x0eCreateShipment\x12*.shipping_service.v1.CreateShipmentRequest\x1a+.shipping_service.v1.CreateShipmentResponse\x12\x81\x01\n" +
	"\x16RegisterTrackingNumber\x122.shipping_service.v1.RegisterTrackingNumberRequest\x1a3.shipping_service.v1.RegisterTrackingNumberResponse\x12{\n" +
	"\x14UpdateShipmentStatus\x120.shipping_service.v1.UpdateShipmentStatusRequest\x1a1.shipping_service.v1.UpdateShipmentStatusResponse\x12r\n" +
	"\x11GetShipmentDetail\x12-.shipping_service.v1.GetShipmentDetailRequest\x1a..shipping_service.v1.GetShipmentDetailResponse\x12u\n" +
	"\x12GetShipmentByOrder\x12..shipping_service.v1.GetShipmentByOrderRequest\x1a/.shipping_service.v1.GetShipmentByOrderResponse\x12x\n" +
	"\x13SyncCarrierTracking\x12/.shipping_service.v1.SyncCarrierTrackingRequest\x1a0.shipping_service.v1.SyncCarrierTrackingResponse\x12l\n" +
	"\x0fValidateAddress\x12+.shipping_service.v1.ValidateAddressRequest\x1a,.shipping_service.v1.ValidateAddressResponse\x12o\n" +
	"\x10NormalizeAddress\x12,.shipping_service.v1.NormalizeAddressRequest\x1a-.shipping_service.v1.NormalizeAddressResponseBOZMgithub.com/makoto-developer/go_microservice_example/proto/shipping_service/v1b\x06proto3"

var (
	file_shipping_service_v1_shipping_service_proto_rawDescOnce sync.Once
	file_shipping_service_v1_shipping_service_proto_rawDescData []byte
)

func file_shipping_service_v1_shipping_service_proto_rawDescGZIP() []byte {
	file_shipping_service_v1_shipping_service_proto_rawDescOnce.Do(func() {
		file_shipping_service_v1_shipping_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_service_v1_shipping_service_proto_rawDesc), len(file_shipping_service_v1_shipping_service_proto_rawDesc)))
	})
	return file_shipping_service_v1_shipping_service_proto_rawDescData
}

var file_shipping_service_v1_shipping_service_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_shipping_service_v1_shipping_service_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_shipping_service_v1_shipping_service_proto_goTypes = []any{
	(Carrier)(0),                           // 0: shipping_service.v1.Carrier
	(ShipmentStatus)(0),                    // 1: shipping_service.v1.ShipmentStatus
	(TimeSlot)(0),                          // 2: shipping_service.v1.TimeSlot
	(DeliveryOption)(0),                    // 3: shipping_service.v1.DeliveryOption
	(*ShippingMethod)(nil),                 // 4: shipping_service.v1.ShippingMethod
	(*ShippingRate)(nil),                   // 5: shipping_service.v1.ShippingRate
	(*Shipment)(nil),                       // 6: shipping_service.v1.Shipment
	(*ShipmentHistory)(nil),                // 7: shipping_service.v1.ShipmentHistory
	(*CarrierTracking)(nil),                // 8: shipping_service.v1.CarrierTracking
	(*CalculateShippingFeeRequest)(nil),    // 9: shipping_service.v1.CalculateShippingFeeRequest
	(*CreateShipmentRequest)(nil),          // 10: shipping_service.v1.CreateShipmentRequest
	(*RegisterTrackingNumberRequest)(nil),  // 11: shipping_service.v1.RegisterTrackingNumberRequest
	(*UpdateShipmentStatusRequest)(nil),    // 12: shipping_service.v1.UpdateShipmentStatusRequest
	(*GetShipmentDetailRequest)(nil),       // 13: shipping_service.v1.GetShipmentDetailRequest
	(*GetShipmentByOrderRequest)(nil),      // 14: shipping_service.v1.GetShipmentByOrderRequest
	(*SyncCarrierTrackingRequest)(nil),     // 15: shipping_service.v1.SyncCarrierTrackingRequest
	(*BatchSyncAllShipmentsRequest)(nil),   // 16: shipping_service.v1.BatchSyncAllShipmentsRequest
	(*BatchSyncAllShipmentsResponse)(nil),  // 17: shipping_service.v1.BatchSyncAllShipmentsResponse
	(*ValidateAddressRequest)(nil),         // 18: shipping_service.v1.ValidateAddressRequest
	(*NormalizeAddressRequest)(nil),        // 19: shipping_service.v1.NormalizeAddressRequest
	(*CalculateShippingFeeResponse)(nil),   // 20: shipping_service.v1.CalculateShippingFeeResponse
	(*CreateShipmentResponse)(nil),         // 21: shipping_service.v1.CreateShipmentResponse
	(*RegisterTrackingNumberResponse)(nil), // 22: shipping_service.v1.RegisterTrackingNumberResponse
	(*UpdateShipmentStatusResponse)(nil),   // 23: shipping_service.v1.UpdateShipmentStatusResponse
	(*GetShipmentDetailResponse)(nil),      // 24: shipping_service.v1.GetShipmentDetailResponse
	(*GetShipmentByOrderResponse)(nil),     // 25: shipping_service.v1.GetShipmentByOrderResponse
	(*SyncCarrierTrackingResponse)(nil),    // 26: shipping_service.v1.SyncCarrierTrackingResponse
	(*ValidateAddressResponse)(nil),        // 27: shipping_service.v1.ValidateAddressResponse
	(*NormalizeAddressResponse)(nil),       // 28: shipping_service.v1.NormalizeAddressResponse
	(*timestamppb.Timestamp)(nil),          // 29: google.protobuf.Timestamp
}
var file_shipping_service_v1_shipping_service_proto_depIdxs = []int32{
	0,  // 0: shipping_service.v1.ShippingMethod.carrier:type_name -> shipping_service.v1.Carrier
	29, // 1: shipping_service.v1.ShippingMethod.created_at:type_name -> google.protobuf.Timestamp
	29, // 2: shipping_service.v1.ShippingMethod.updated_at:type_name -> google.protobuf.Timestamp
	29, // 3: shipping_service.v1.ShippingRate.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: shipping_service.v1.Shipment.carrier:type_name -> shipping_service.v1.Carrier
	1,  // 5: shipping_service.v1.Shipment.status:type_name -> shipping_service.v1.ShipmentStatus
	2,  // 6: shipping_service.v1.Shipment.delivery_time_slot:type_name -> shipping_service.v1.TimeSlot
	3,  // 7: shipping_service.v1.Shipment.delivery_option:type_name -> shipping_service.v1.DeliveryOption
	29, // 8: shipping_service.v1.Shipment.dispatched_at:type_name -> google.protobuf.Timestamp
	29, // 9: shipping_service.v1.Shipment.delivered_at:type_name -> google.protobuf.Timestamp
	29, // 10: shipping_service.v1.Shipment.created_at:type_name -> google.protobuf.Timestamp
	29, // 11: shipping_service.v1.Shipment.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 12: shipping_service.v1.ShipmentHistory.old_status:type_name -> shipping_service.v1.ShipmentStatus
	1,  // 13: shipping_service.v1.ShipmentHistory.new_status:type_name -> shipping_service.v1.ShipmentStatus
	29, // 14: shipping_service.v1.ShipmentHistory.created_at:type_name -> google.protobuf.Timestamp
	0,  // 15: shipping_service.v1.CarrierTracking.carrier:type_name -> shipping_service.v1.Carrier
	29, // 16: shipping_service.v1.CarrierTracking.last_updated_at:type_name -> google.protobuf.Timestamp
	29, // 17: shipping_service.v1.CarrierTracking.created_at:type_name -> google.protobuf.Timestamp
	29, // 18: shipping_service.v1.CarrierTracking.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 19: shipping_service.v1.CreateShipmentRequest.delivery_time_slot:type_name -> shipping_service.v1.TimeSlot
	3,  // 20: shipping_service.v1.CreateShipmentRequest.delivery_option:type_name -> shipping_service.v1.DeliveryOption
	0,  // 21: shipping_service.v1.RegisterTrackingNumberRequest.carrier:type_name -> shipping_service.v1.Carrier
	1,  // 22: shipping_service.v1.UpdateShipmentStatusRequest.new_status:type_name -> shipping_service.v1.ShipmentStatus
	9,  // 23: shipping_service.v1.ShippingService.CalculateShippingFee:input_type -> shipping_service.v1.CalculateShippingFeeRequest
	10, // 24: shipping_service.v1.ShippingService.CreateShipment:input_type -> shipping_service.v1.CreateShipmentRequest
	11, // 25: shipping_service.v1.ShippingService.RegisterTrackingNumber:input_type -> shipping_service.v1.RegisterTrackingNumberRequest
	12, // 26: shipping_service.v1.ShippingService.UpdateShipmentStatus:input_type -> shipping_service.v1.UpdateShipmentStatusRequest
	13, // 27: shipping_service.v1.ShippingService.GetShipmentDetail:input_type -> shipping_service.v1.GetShipmentDetailRequest
	14, // 28: shipping_service.v1.ShippingService.GetShipmentByOrder:input_type -> shipping_service.v1.GetShipmentByOrderRequest
	15, // 29: shipping_service.v1.ShippingService.SyncCarrierTracking:input_type -> shipping_service.v1.SyncCarrierTrackingRequest
	18, // 30: shipping_service.v1.ShippingService.ValidateAddress:input_type -> shipping_service.v1.ValidateAddressRequest
	19, // 31: shipping_service.v1.ShippingService.NormalizeAddress:input_type -> shipping_service.v1.NormalizeAddressRequest
	20, // 32: shipping_service.v1.ShippingService.CalculateShippingFee:output_type -> shipping_service.v1.CalculateShippingFeeResponse
	21, // 33: shipping_service.v1.ShippingService.CreateShipment:output_type -> shipping_service.v1.CreateShipmentResponse
	22, // 34: shipping_service.v1.ShippingService.RegisterTrackingNumber:output_type -> shipping_service.v1.RegisterTrackingNumberResponse
	23, // 35: shipping_service.v1.ShippingService.UpdateShipmentStatus:output_type -> shipping_service.v1.UpdateShipmentStatusResponse
	24, // 36: shipping_service.v1.ShippingService.GetShipmentDetail:output_type -> shipping_service.v1.GetShipmentDetailResponse
	25, // 37: shipping_service.v1.ShippingService.GetShipmentByOrder:output_type -> shipping_service.v1.GetShipmentByOrderResponse
	26, // 38: shipping_service.v1.ShippingService.SyncCarrierTracking:output_type -> shipping_service.v1.SyncCarrierTrackingResponse
	27, // 39: shipping_service.v1.ShippingService.ValidateAddress:output_type -> shipping_service.v1.ValidateAddressResponse
	28, // 40: shipping_service.v1.ShippingService.NormalizeAddress:output_type -> shipping_service.v1.NormalizeAddressResponse
	32, // [32:41] is the sub-list for method output_type
	23, // [23:32] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_shipping_service_v1_shipping_service_proto_init() }
func file_shipping_service_v1_shipping_service_proto_init() {
	if File_shipping_service_v1_shipping_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_service_v1_shipping_service_proto_rawDesc), len(file_shipping_service_v1_shipping_service_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipping_service_v1_shipping_service_proto_goTypes,
		DependencyIndexes: file_shipping_service_v1_shipping_service_proto_depIdxs,
		EnumInfos:         file_shipping_service_v1_shipping_service_proto_enumTypes,
		MessageInfos:      file_shipping_service_v1_shipping_service_proto_msgTypes,
	}.Build()
	File_shipping_service_v1_shipping_service_proto = out.File
	file_shipping_service_v1_shipping_service_proto_goTypes = nil
	file_shipping_service_v1_shipping_service_proto_depIdxs = nil
}
