// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: search-service/v1/search-service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchService_SearchProducts_FullMethodName        = "/search_service.v1.SearchService/SearchProducts"
	SearchService_GetSearchSuggestions_FullMethodName  = "/search_service.v1.SearchService/GetSearchSuggestions"
	SearchService_SearchShops_FullMethodName           = "/search_service.v1.SearchService/SearchShops"
	SearchService_RecordSearchHistory_FullMethodName   = "/search_service.v1.SearchService/RecordSearchHistory"
	SearchService_GetSearchHistory_FullMethodName      = "/search_service.v1.SearchService/GetSearchHistory"
	SearchService_DeleteSearchHistory_FullMethodName   = "/search_service.v1.SearchService/DeleteSearchHistory"
	SearchService_ClearAllSearchHistory_FullMethodName = "/search_service.v1.SearchService/ClearAllSearchHistory"
	SearchService_GetPopularKeywords_FullMethodName    = "/search_service.v1.SearchService/GetPopularKeywords"
	SearchService_GetTrendingKeywords_FullMethodName   = "/search_service.v1.SearchService/GetTrendingKeywords"
	SearchService_IndexProduct_FullMethodName          = "/search_service.v1.SearchService/IndexProduct"
	SearchService_UpdateProductIndex_FullMethodName    = "/search_service.v1.SearchService/UpdateProductIndex"
	SearchService_DeleteProductIndex_FullMethodName    = "/search_service.v1.SearchService/DeleteProductIndex"
	SearchService_IndexShop_FullMethodName             = "/search_service.v1.SearchService/IndexShop"
	SearchService_DeleteShopIndex_FullMethodName       = "/search_service.v1.SearchService/DeleteShopIndex"
	SearchService_GetSearchAnalytics_FullMethodName    = "/search_service.v1.SearchService/GetSearchAnalytics"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error)
	GetSearchSuggestions(ctx context.Context, in *GetSearchSuggestionsRequest, opts ...grpc.CallOption) (*GetSearchSuggestionsResponse, error)
	SearchShops(ctx context.Context, in *SearchShopsRequest, opts ...grpc.CallOption) (*SearchShopsResponse, error)
	RecordSearchHistory(ctx context.Context, in *RecordSearchHistoryRequest, opts ...grpc.CallOption) (*RecordSearchHistoryResponse, error)
	GetSearchHistory(ctx context.Context, in *GetSearchHistoryRequest, opts ...grpc.CallOption) (*GetSearchHistoryResponse, error)
	DeleteSearchHistory(ctx context.Context, in *DeleteSearchHistoryRequest, opts ...grpc.CallOption) (*DeleteSearchHistoryResponse, error)
	ClearAllSearchHistory(ctx context.Context, in *ClearAllSearchHistoryRequest, opts ...grpc.CallOption) (*ClearAllSearchHistoryResponse, error)
	GetPopularKeywords(ctx context.Context, in *GetPopularKeywordsRequest, opts ...grpc.CallOption) (*GetPopularKeywordsResponse, error)
	GetTrendingKeywords(ctx context.Context, in *GetTrendingKeywordsRequest, opts ...grpc.CallOption) (*GetTrendingKeywordsResponse, error)
	IndexProduct(ctx context.Context, in *IndexProductRequest, opts ...grpc.CallOption) (*IndexProductResponse, error)
	UpdateProductIndex(ctx context.Context, in *UpdateProductIndexRequest, opts ...grpc.CallOption) (*UpdateProductIndexResponse, error)
	DeleteProductIndex(ctx context.Context, in *DeleteProductIndexRequest, opts ...grpc.CallOption) (*DeleteProductIndexResponse, error)
	IndexShop(ctx context.Context, in *IndexShopRequest, opts ...grpc.CallOption) (*IndexShopResponse, error)
	DeleteShopIndex(ctx context.Context, in *DeleteShopIndexRequest, opts ...grpc.CallOption) (*DeleteShopIndexResponse, error)
	GetSearchAnalytics(ctx context.Context, in *GetSearchAnalyticsRequest, opts ...grpc.CallOption) (*GetSearchAnalyticsResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProductsResponse)
	err := c.cc.Invoke(ctx, SearchService_SearchProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetSearchSuggestions(ctx context.Context, in *GetSearchSuggestionsRequest, opts ...grpc.CallOption) (*GetSearchSuggestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSearchSuggestionsResponse)
	err := c.cc.Invoke(ctx, SearchService_GetSearchSuggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) SearchShops(ctx context.Context, in *SearchShopsRequest, opts ...grpc.CallOption) (*SearchShopsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchShopsResponse)
	err := c.cc.Invoke(ctx, SearchService_SearchShops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) RecordSearchHistory(ctx context.Context, in *RecordSearchHistoryRequest, opts ...grpc.CallOption) (*RecordSearchHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordSearchHistoryResponse)
	err := c.cc.Invoke(ctx, SearchService_RecordSearchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetSearchHistory(ctx context.Context, in *GetSearchHistoryRequest, opts ...grpc.CallOption) (*GetSearchHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSearchHistoryResponse)
	err := c.cc.Invoke(ctx, SearchService_GetSearchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) DeleteSearchHistory(ctx context.Context, in *DeleteSearchHistoryRequest, opts ...grpc.CallOption) (*DeleteSearchHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSearchHistoryResponse)
	err := c.cc.Invoke(ctx, SearchService_DeleteSearchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) ClearAllSearchHistory(ctx context.Context, in *ClearAllSearchHistoryRequest, opts ...grpc.CallOption) (*ClearAllSearchHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearAllSearchHistoryResponse)
	err := c.cc.Invoke(ctx, SearchService_ClearAllSearchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetPopularKeywords(ctx context.Context, in *GetPopularKeywordsRequest, opts ...grpc.CallOption) (*GetPopularKeywordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPopularKeywordsResponse)
	err := c.cc.Invoke(ctx, SearchService_GetPopularKeywords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetTrendingKeywords(ctx context.Context, in *GetTrendingKeywordsRequest, opts ...grpc.CallOption) (*GetTrendingKeywordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrendingKeywordsResponse)
	err := c.cc.Invoke(ctx, SearchService_GetTrendingKeywords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) IndexProduct(ctx context.Context, in *IndexProductRequest, opts ...grpc.CallOption) (*IndexProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexProductResponse)
	err := c.cc.Invoke(ctx, SearchService_IndexProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) UpdateProductIndex(ctx context.Context, in *UpdateProductIndexRequest, opts ...grpc.CallOption) (*UpdateProductIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductIndexResponse)
	err := c.cc.Invoke(ctx, SearchService_UpdateProductIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) DeleteProductIndex(ctx context.Context, in *DeleteProductIndexRequest, opts ...grpc.CallOption) (*DeleteProductIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductIndexResponse)
	err := c.cc.Invoke(ctx, SearchService_DeleteProductIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) IndexShop(ctx context.Context, in *IndexShopRequest, opts ...grpc.CallOption) (*IndexShopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexShopResponse)
	err := c.cc.Invoke(ctx, SearchService_IndexShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) DeleteShopIndex(ctx context.Context, in *DeleteShopIndexRequest, opts ...grpc.CallOption) (*DeleteShopIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteShopIndexResponse)
	err := c.cc.Invoke(ctx, SearchService_DeleteShopIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetSearchAnalytics(ctx context.Context, in *GetSearchAnalyticsRequest, opts ...grpc.CallOption) (*GetSearchAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSearchAnalyticsResponse)
	err := c.cc.Invoke(ctx, SearchService_GetSearchAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility.
type SearchServiceServer interface {
	SearchProducts(context.Context, *SearchProductsRequest) (*SearchProductsResponse, error)
	GetSearchSuggestions(context.Context, *GetSearchSuggestionsRequest) (*GetSearchSuggestionsResponse, error)
	SearchShops(context.Context, *SearchShopsRequest) (*SearchShopsResponse, error)
	RecordSearchHistory(context.Context, *RecordSearchHistoryRequest) (*RecordSearchHistoryResponse, error)
	GetSearchHistory(context.Context, *GetSearchHistoryRequest) (*GetSearchHistoryResponse, error)
	DeleteSearchHistory(context.Context, *DeleteSearchHistoryRequest) (*DeleteSearchHistoryResponse, error)
	ClearAllSearchHistory(context.Context, *ClearAllSearchHistoryRequest) (*ClearAllSearchHistoryResponse, error)
	GetPopularKeywords(context.Context, *GetPopularKeywordsRequest) (*GetPopularKeywordsResponse, error)
	GetTrendingKeywords(context.Context, *GetTrendingKeywordsRequest) (*GetTrendingKeywordsResponse, error)
	IndexProduct(context.Context, *IndexProductRequest) (*IndexProductResponse, error)
	UpdateProductIndex(context.Context, *UpdateProductIndexRequest) (*UpdateProductIndexResponse, error)
	DeleteProductIndex(context.Context, *DeleteProductIndexRequest) (*DeleteProductIndexResponse, error)
	IndexShop(context.Context, *IndexShopRequest) (*IndexShopResponse, error)
	DeleteShopIndex(context.Context, *DeleteShopIndexRequest) (*DeleteShopIndexResponse, error)
	GetSearchAnalytics(context.Context, *GetSearchAnalyticsRequest) (*GetSearchAnalyticsResponse, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServiceServer struct{}

func (UnimplementedSearchServiceServer) SearchProducts(context.Context, *SearchProductsRequest) (*SearchProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchProducts not implemented")
}
func (UnimplementedSearchServiceServer) GetSearchSuggestions(context.Context, *GetSearchSuggestionsRequest) (*GetSearchSuggestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSearchSuggestions not implemented")
}
func (UnimplementedSearchServiceServer) SearchShops(context.Context, *SearchShopsRequest) (*SearchShopsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchShops not implemented")
}
func (UnimplementedSearchServiceServer) RecordSearchHistory(context.Context, *RecordSearchHistoryRequest) (*RecordSearchHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordSearchHistory not implemented")
}
func (UnimplementedSearchServiceServer) GetSearchHistory(context.Context, *GetSearchHistoryRequest) (*GetSearchHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSearchHistory not implemented")
}
func (UnimplementedSearchServiceServer) DeleteSearchHistory(context.Context, *DeleteSearchHistoryRequest) (*DeleteSearchHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSearchHistory not implemented")
}
func (UnimplementedSearchServiceServer) ClearAllSearchHistory(context.Context, *ClearAllSearchHistoryRequest) (*ClearAllSearchHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearAllSearchHistory not implemented")
}
func (UnimplementedSearchServiceServer) GetPopularKeywords(context.Context, *GetPopularKeywordsRequest) (*GetPopularKeywordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPopularKeywords not implemented")
}
func (UnimplementedSearchServiceServer) GetTrendingKeywords(context.Context, *GetTrendingKeywordsRequest) (*GetTrendingKeywordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrendingKeywords not implemented")
}
func (UnimplementedSearchServiceServer) IndexProduct(context.Context, *IndexProductRequest) (*IndexProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexProduct not implemented")
}
func (UnimplementedSearchServiceServer) UpdateProductIndex(context.Context, *UpdateProductIndexRequest) (*UpdateProductIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProductIndex not implemented")
}
func (UnimplementedSearchServiceServer) DeleteProductIndex(context.Context, *DeleteProductIndexRequest) (*DeleteProductIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProductIndex not implemented")
}
func (UnimplementedSearchServiceServer) IndexShop(context.Context, *IndexShopRequest) (*IndexShopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexShop not implemented")
}
func (UnimplementedSearchServiceServer) DeleteShopIndex(context.Context, *DeleteShopIndexRequest) (*DeleteShopIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShopIndex not implemented")
}
func (UnimplementedSearchServiceServer) GetSearchAnalytics(context.Context, *GetSearchAnalyticsRequest) (*GetSearchAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSearchAnalytics not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}
func (UnimplementedSearchServiceServer) testEmbeddedByValue()                       {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	// If the following call panics, it indicates UnimplementedSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_SearchProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchProducts(ctx, req.(*SearchProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetSearchSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSearchSuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetSearchSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetSearchSuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetSearchSuggestions(ctx, req.(*GetSearchSuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_SearchShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchShopsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchShops(ctx, req.(*SearchShopsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_RecordSearchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordSearchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).RecordSearchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_RecordSearchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).RecordSearchHistory(ctx, req.(*RecordSearchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetSearchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSearchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetSearchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetSearchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetSearchHistory(ctx, req.(*GetSearchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_DeleteSearchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSearchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).DeleteSearchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_DeleteSearchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).DeleteSearchHistory(ctx, req.(*DeleteSearchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_ClearAllSearchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearAllSearchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).ClearAllSearchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_ClearAllSearchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).ClearAllSearchHistory(ctx, req.(*ClearAllSearchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetPopularKeywords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPopularKeywordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetPopularKeywords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetPopularKeywords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetPopularKeywords(ctx, req.(*GetPopularKeywordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetTrendingKeywords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendingKeywordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetTrendingKeywords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetTrendingKeywords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetTrendingKeywords(ctx, req.(*GetTrendingKeywordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_IndexProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).IndexProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_IndexProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).IndexProduct(ctx, req.(*IndexProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_UpdateProductIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).UpdateProductIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_UpdateProductIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).UpdateProductIndex(ctx, req.(*UpdateProductIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_DeleteProductIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).DeleteProductIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_DeleteProductIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).DeleteProductIndex(ctx, req.(*DeleteProductIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_IndexShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).IndexShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_IndexShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).IndexShop(ctx, req.(*IndexShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_DeleteShopIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShopIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).DeleteShopIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_DeleteShopIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).DeleteShopIndex(ctx, req.(*DeleteShopIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetSearchAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSearchAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetSearchAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetSearchAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetSearchAnalytics(ctx, req.(*GetSearchAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search_service.v1.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchProducts",
			Handler:    _SearchService_SearchProducts_Handler,
		},
		{
			MethodName: "GetSearchSuggestions",
			Handler:    _SearchService_GetSearchSuggestions_Handler,
		},
		{
			MethodName: "SearchShops",
			Handler:    _SearchService_SearchShops_Handler,
		},
		{
			MethodName: "RecordSearchHistory",
			Handler:    _SearchService_RecordSearchHistory_Handler,
		},
		{
			MethodName: "GetSearchHistory",
			Handler:    _SearchService_GetSearchHistory_Handler,
		},
		{
			MethodName: "DeleteSearchHistory",
			Handler:    _SearchService_DeleteSearchHistory_Handler,
		},
		{
			MethodName: "ClearAllSearchHistory",
			Handler:    _SearchService_ClearAllSearchHistory_Handler,
		},
		{
			MethodName: "GetPopularKeywords",
			Handler:    _SearchService_GetPopularKeywords_Handler,
		},
		{
			MethodName: "GetTrendingKeywords",
			Handler:    _SearchService_GetTrendingKeywords_Handler,
		},
		{
			MethodName: "IndexProduct",
			Handler:    _SearchService_IndexProduct_Handler,
		},
		{
			MethodName: "UpdateProductIndex",
			Handler:    _SearchService_UpdateProductIndex_Handler,
		},
		{
			MethodName: "DeleteProductIndex",
			Handler:    _SearchService_DeleteProductIndex_Handler,
		},
		{
			MethodName: "IndexShop",
			Handler:    _SearchService_IndexShop_Handler,
		},
		{
			MethodName: "DeleteShopIndex",
			Handler:    _SearchService_DeleteShopIndex_Handler,
		},
		{
			MethodName: "GetSearchAnalytics",
			Handler:    _SearchService_GetSearchAnalytics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search-service/v1/search-service.proto",
}
