// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: inventory-service/v1/inventory-service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_RegisterInventory_FullMethodName          = "/inventory_service.v1.InventoryService/RegisterInventory"
	InventoryService_UpdateInventoryQuantity_FullMethodName    = "/inventory_service.v1.InventoryService/UpdateInventoryQuantity"
	InventoryService_GetInventory_FullMethodName               = "/inventory_service.v1.InventoryService/GetInventory"
	InventoryService_GetInventoryByProduct_FullMethodName      = "/inventory_service.v1.InventoryService/GetInventoryByProduct"
	InventoryService_BulkGetInventory_FullMethodName           = "/inventory_service.v1.InventoryService/BulkGetInventory"
	InventoryService_ReserveStock_FullMethodName               = "/inventory_service.v1.InventoryService/ReserveStock"
	InventoryService_BulkReserveStock_FullMethodName           = "/inventory_service.v1.InventoryService/BulkReserveStock"
	InventoryService_ReleaseStock_FullMethodName               = "/inventory_service.v1.InventoryService/ReleaseStock"
	InventoryService_ConfirmStock_FullMethodName               = "/inventory_service.v1.InventoryService/ConfirmStock"
	InventoryService_ReleaseExpiredReservations_FullMethodName = "/inventory_service.v1.InventoryService/ReleaseExpiredReservations"
	InventoryService_CheckStockAlert_FullMethodName            = "/inventory_service.v1.InventoryService/CheckStockAlert"
	InventoryService_GetInventoryHistory_FullMethodName        = "/inventory_service.v1.InventoryService/GetInventoryHistory"
	InventoryService_RecordStockTaking_FullMethodName          = "/inventory_service.v1.InventoryService/RecordStockTaking"
	InventoryService_GetStockTakingHistory_FullMethodName      = "/inventory_service.v1.InventoryService/GetStockTakingHistory"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryServiceClient interface {
	RegisterInventory(ctx context.Context, in *RegisterInventoryRequest, opts ...grpc.CallOption) (*RegisterInventoryResponse, error)
	UpdateInventoryQuantity(ctx context.Context, in *UpdateInventoryQuantityRequest, opts ...grpc.CallOption) (*UpdateInventoryQuantityResponse, error)
	GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error)
	GetInventoryByProduct(ctx context.Context, in *GetInventoryByProductRequest, opts ...grpc.CallOption) (*GetInventoryByProductResponse, error)
	BulkGetInventory(ctx context.Context, in *BulkGetInventoryRequest, opts ...grpc.CallOption) (*BulkGetInventoryResponse, error)
	ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserveStockResponse, error)
	BulkReserveStock(ctx context.Context, in *BulkReserveStockRequest, opts ...grpc.CallOption) (*BulkReserveStockResponse, error)
	ReleaseStock(ctx context.Context, in *ReleaseStockRequest, opts ...grpc.CallOption) (*ReleaseStockResponse, error)
	ConfirmStock(ctx context.Context, in *ConfirmStockRequest, opts ...grpc.CallOption) (*ConfirmStockResponse, error)
	ReleaseExpiredReservations(ctx context.Context, in *ReleaseExpiredReservationsRequest, opts ...grpc.CallOption) (*ReleaseExpiredReservationsResponse, error)
	CheckStockAlert(ctx context.Context, in *CheckStockAlertRequest, opts ...grpc.CallOption) (*CheckStockAlertResponse, error)
	GetInventoryHistory(ctx context.Context, in *GetInventoryHistoryRequest, opts ...grpc.CallOption) (*GetInventoryHistoryResponse, error)
	RecordStockTaking(ctx context.Context, in *RecordStockTakingRequest, opts ...grpc.CallOption) (*RecordStockTakingResponse, error)
	GetStockTakingHistory(ctx context.Context, in *GetStockTakingHistoryRequest, opts ...grpc.CallOption) (*GetStockTakingHistoryResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) RegisterInventory(ctx context.Context, in *RegisterInventoryRequest, opts ...grpc.CallOption) (*RegisterInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterInventoryResponse)
	err := c.cc.Invoke(ctx, InventoryService_RegisterInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) UpdateInventoryQuantity(ctx context.Context, in *UpdateInventoryQuantityRequest, opts ...grpc.CallOption) (*UpdateInventoryQuantityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInventoryQuantityResponse)
	err := c.cc.Invoke(ctx, InventoryService_UpdateInventoryQuantity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventoryResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetInventoryByProduct(ctx context.Context, in *GetInventoryByProductRequest, opts ...grpc.CallOption) (*GetInventoryByProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventoryByProductResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetInventoryByProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) BulkGetInventory(ctx context.Context, in *BulkGetInventoryRequest, opts ...grpc.CallOption) (*BulkGetInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkGetInventoryResponse)
	err := c.cc.Invoke(ctx, InventoryService_BulkGetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserveStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveStockResponse)
	err := c.cc.Invoke(ctx, InventoryService_ReserveStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) BulkReserveStock(ctx context.Context, in *BulkReserveStockRequest, opts ...grpc.CallOption) (*BulkReserveStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkReserveStockResponse)
	err := c.cc.Invoke(ctx, InventoryService_BulkReserveStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ReleaseStock(ctx context.Context, in *ReleaseStockRequest, opts ...grpc.CallOption) (*ReleaseStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseStockResponse)
	err := c.cc.Invoke(ctx, InventoryService_ReleaseStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ConfirmStock(ctx context.Context, in *ConfirmStockRequest, opts ...grpc.CallOption) (*ConfirmStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmStockResponse)
	err := c.cc.Invoke(ctx, InventoryService_ConfirmStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ReleaseExpiredReservations(ctx context.Context, in *ReleaseExpiredReservationsRequest, opts ...grpc.CallOption) (*ReleaseExpiredReservationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseExpiredReservationsResponse)
	err := c.cc.Invoke(ctx, InventoryService_ReleaseExpiredReservations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) CheckStockAlert(ctx context.Context, in *CheckStockAlertRequest, opts ...grpc.CallOption) (*CheckStockAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckStockAlertResponse)
	err := c.cc.Invoke(ctx, InventoryService_CheckStockAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetInventoryHistory(ctx context.Context, in *GetInventoryHistoryRequest, opts ...grpc.CallOption) (*GetInventoryHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventoryHistoryResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetInventoryHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) RecordStockTaking(ctx context.Context, in *RecordStockTakingRequest, opts ...grpc.CallOption) (*RecordStockTakingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordStockTakingResponse)
	err := c.cc.Invoke(ctx, InventoryService_RecordStockTaking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetStockTakingHistory(ctx context.Context, in *GetStockTakingHistoryRequest, opts ...grpc.CallOption) (*GetStockTakingHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockTakingHistoryResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetStockTakingHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
type InventoryServiceServer interface {
	RegisterInventory(context.Context, *RegisterInventoryRequest) (*RegisterInventoryResponse, error)
	UpdateInventoryQuantity(context.Context, *UpdateInventoryQuantityRequest) (*UpdateInventoryQuantityResponse, error)
	GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error)
	GetInventoryByProduct(context.Context, *GetInventoryByProductRequest) (*GetInventoryByProductResponse, error)
	BulkGetInventory(context.Context, *BulkGetInventoryRequest) (*BulkGetInventoryResponse, error)
	ReserveStock(context.Context, *ReserveStockRequest) (*ReserveStockResponse, error)
	BulkReserveStock(context.Context, *BulkReserveStockRequest) (*BulkReserveStockResponse, error)
	ReleaseStock(context.Context, *ReleaseStockRequest) (*ReleaseStockResponse, error)
	ConfirmStock(context.Context, *ConfirmStockRequest) (*ConfirmStockResponse, error)
	ReleaseExpiredReservations(context.Context, *ReleaseExpiredReservationsRequest) (*ReleaseExpiredReservationsResponse, error)
	CheckStockAlert(context.Context, *CheckStockAlertRequest) (*CheckStockAlertResponse, error)
	GetInventoryHistory(context.Context, *GetInventoryHistoryRequest) (*GetInventoryHistoryResponse, error)
	RecordStockTaking(context.Context, *RecordStockTakingRequest) (*RecordStockTakingResponse, error)
	GetStockTakingHistory(context.Context, *GetStockTakingHistoryRequest) (*GetStockTakingHistoryResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) RegisterInventory(context.Context, *RegisterInventoryRequest) (*RegisterInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterInventory not implemented")
}
func (UnimplementedInventoryServiceServer) UpdateInventoryQuantity(context.Context, *UpdateInventoryQuantityRequest) (*UpdateInventoryQuantityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateInventoryQuantity not implemented")
}
func (UnimplementedInventoryServiceServer) GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventory not implemented")
}
func (UnimplementedInventoryServiceServer) GetInventoryByProduct(context.Context, *GetInventoryByProductRequest) (*GetInventoryByProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventoryByProduct not implemented")
}
func (UnimplementedInventoryServiceServer) BulkGetInventory(context.Context, *BulkGetInventoryRequest) (*BulkGetInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkGetInventory not implemented")
}
func (UnimplementedInventoryServiceServer) ReserveStock(context.Context, *ReserveStockRequest) (*ReserveStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveStock not implemented")
}
func (UnimplementedInventoryServiceServer) BulkReserveStock(context.Context, *BulkReserveStockRequest) (*BulkReserveStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkReserveStock not implemented")
}
func (UnimplementedInventoryServiceServer) ReleaseStock(context.Context, *ReleaseStockRequest) (*ReleaseStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseStock not implemented")
}
func (UnimplementedInventoryServiceServer) ConfirmStock(context.Context, *ConfirmStockRequest) (*ConfirmStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmStock not implemented")
}
func (UnimplementedInventoryServiceServer) ReleaseExpiredReservations(context.Context, *ReleaseExpiredReservationsRequest) (*ReleaseExpiredReservationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseExpiredReservations not implemented")
}
func (UnimplementedInventoryServiceServer) CheckStockAlert(context.Context, *CheckStockAlertRequest) (*CheckStockAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckStockAlert not implemented")
}
func (UnimplementedInventoryServiceServer) GetInventoryHistory(context.Context, *GetInventoryHistoryRequest) (*GetInventoryHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventoryHistory not implemented")
}
func (UnimplementedInventoryServiceServer) RecordStockTaking(context.Context, *RecordStockTakingRequest) (*RecordStockTakingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordStockTaking not implemented")
}
func (UnimplementedInventoryServiceServer) GetStockTakingHistory(context.Context, *GetStockTakingHistoryRequest) (*GetStockTakingHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStockTakingHistory not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_RegisterInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).RegisterInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_RegisterInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).RegisterInventory(ctx, req.(*RegisterInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_UpdateInventoryQuantity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInventoryQuantityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).UpdateInventoryQuantity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_UpdateInventoryQuantity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).UpdateInventoryQuantity(ctx, req.(*UpdateInventoryQuantityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetInventory(ctx, req.(*GetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetInventoryByProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryByProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetInventoryByProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetInventoryByProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetInventoryByProduct(ctx, req.(*GetInventoryByProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_BulkGetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkGetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).BulkGetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_BulkGetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).BulkGetInventory(ctx, req.(*BulkGetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ReserveStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ReserveStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ReserveStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ReserveStock(ctx, req.(*ReserveStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_BulkReserveStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkReserveStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).BulkReserveStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_BulkReserveStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).BulkReserveStock(ctx, req.(*BulkReserveStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ReleaseStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ReleaseStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ReleaseStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ReleaseStock(ctx, req.(*ReleaseStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ConfirmStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ConfirmStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ConfirmStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ConfirmStock(ctx, req.(*ConfirmStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ReleaseExpiredReservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseExpiredReservationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ReleaseExpiredReservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ReleaseExpiredReservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ReleaseExpiredReservations(ctx, req.(*ReleaseExpiredReservationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_CheckStockAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStockAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CheckStockAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CheckStockAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CheckStockAlert(ctx, req.(*CheckStockAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetInventoryHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetInventoryHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetInventoryHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetInventoryHistory(ctx, req.(*GetInventoryHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_RecordStockTaking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordStockTakingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).RecordStockTaking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_RecordStockTaking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).RecordStockTaking(ctx, req.(*RecordStockTakingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetStockTakingHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockTakingHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetStockTakingHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetStockTakingHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetStockTakingHistory(ctx, req.(*GetStockTakingHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory_service.v1.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterInventory",
			Handler:    _InventoryService_RegisterInventory_Handler,
		},
		{
			MethodName: "UpdateInventoryQuantity",
			Handler:    _InventoryService_UpdateInventoryQuantity_Handler,
		},
		{
			MethodName: "GetInventory",
			Handler:    _InventoryService_GetInventory_Handler,
		},
		{
			MethodName: "GetInventoryByProduct",
			Handler:    _InventoryService_GetInventoryByProduct_Handler,
		},
		{
			MethodName: "BulkGetInventory",
			Handler:    _InventoryService_BulkGetInventory_Handler,
		},
		{
			MethodName: "ReserveStock",
			Handler:    _InventoryService_ReserveStock_Handler,
		},
		{
			MethodName: "BulkReserveStock",
			Handler:    _InventoryService_BulkReserveStock_Handler,
		},
		{
			MethodName: "ReleaseStock",
			Handler:    _InventoryService_ReleaseStock_Handler,
		},
		{
			MethodName: "ConfirmStock",
			Handler:    _InventoryService_ConfirmStock_Handler,
		},
		{
			MethodName: "ReleaseExpiredReservations",
			Handler:    _InventoryService_ReleaseExpiredReservations_Handler,
		},
		{
			MethodName: "CheckStockAlert",
			Handler:    _InventoryService_CheckStockAlert_Handler,
		},
		{
			MethodName: "GetInventoryHistory",
			Handler:    _InventoryService_GetInventoryHistory_Handler,
		},
		{
			MethodName: "RecordStockTaking",
			Handler:    _InventoryService_RecordStockTaking_Handler,
		},
		{
			MethodName: "GetStockTakingHistory",
			Handler:    _InventoryService_GetStockTakingHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory-service/v1/inventory-service.proto",
}
