// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: inventory-service/v1/inventory-service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReservationStatus int32

const (
	ReservationStatus_RESERVATION_STATUS_UNSPECIFIED ReservationStatus = 0
	ReservationStatus_RESERVATION_STATUS_RESERVED    ReservationStatus = 1
	ReservationStatus_RESERVATION_STATUS_CONFIRMED   ReservationStatus = 2
	ReservationStatus_RESERVATION_STATUS_RELEASED    ReservationStatus = 3
	ReservationStatus_RESERVATION_STATUS_EXPIRED     ReservationStatus = 4
)

// Enum value maps for ReservationStatus.
var (
	ReservationStatus_name = map[int32]string{
		0: "RESERVATION_STATUS_UNSPECIFIED",
		1: "RESERVATION_STATUS_RESERVED",
		2: "RESERVATION_STATUS_CONFIRMED",
		3: "RESERVATION_STATUS_RELEASED",
		4: "RESERVATION_STATUS_EXPIRED",
	}
	ReservationStatus_value = map[string]int32{
		"RESERVATION_STATUS_UNSPECIFIED": 0,
		"RESERVATION_STATUS_RESERVED":    1,
		"RESERVATION_STATUS_CONFIRMED":   2,
		"RESERVATION_STATUS_RELEASED":    3,
		"RESERVATION_STATUS_EXPIRED":     4,
	}
)

func (x ReservationStatus) Enum() *ReservationStatus {
	p := new(ReservationStatus)
	*p = x
	return p
}

func (x ReservationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReservationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_service_v1_inventory_service_proto_enumTypes[0].Descriptor()
}

func (ReservationStatus) Type() protoreflect.EnumType {
	return &file_inventory_service_v1_inventory_service_proto_enumTypes[0]
}

func (x ReservationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReservationStatus.Descriptor instead.
func (ReservationStatus) EnumDescriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{0}
}

type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_UNSPECIFIED       ChangeType = 0
	ChangeType_CHANGE_TYPE_INITIAL           ChangeType = 1
	ChangeType_CHANGE_TYPE_RESTOCK           ChangeType = 2
	ChangeType_CHANGE_TYPE_RETURN            ChangeType = 3
	ChangeType_CHANGE_TYPE_RESERVATION       ChangeType = 4
	ChangeType_CHANGE_TYPE_RELEASE           ChangeType = 5
	ChangeType_CHANGE_TYPE_CONFIRMATION      ChangeType = 6
	ChangeType_CHANGE_TYPE_DAMAGE            ChangeType = 7
	ChangeType_CHANGE_TYPE_STOCK_TAKING      ChangeType = 8
	ChangeType_CHANGE_TYPE_MANUAL_ADJUSTMENT ChangeType = 9
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_UNSPECIFIED",
		1: "CHANGE_TYPE_INITIAL",
		2: "CHANGE_TYPE_RESTOCK",
		3: "CHANGE_TYPE_RETURN",
		4: "CHANGE_TYPE_RESERVATION",
		5: "CHANGE_TYPE_RELEASE",
		6: "CHANGE_TYPE_CONFIRMATION",
		7: "CHANGE_TYPE_DAMAGE",
		8: "CHANGE_TYPE_STOCK_TAKING",
		9: "CHANGE_TYPE_MANUAL_ADJUSTMENT",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_UNSPECIFIED":       0,
		"CHANGE_TYPE_INITIAL":           1,
		"CHANGE_TYPE_RESTOCK":           2,
		"CHANGE_TYPE_RETURN":            3,
		"CHANGE_TYPE_RESERVATION":       4,
		"CHANGE_TYPE_RELEASE":           5,
		"CHANGE_TYPE_CONFIRMATION":      6,
		"CHANGE_TYPE_DAMAGE":            7,
		"CHANGE_TYPE_STOCK_TAKING":      8,
		"CHANGE_TYPE_MANUAL_ADJUSTMENT": 9,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_service_v1_inventory_service_proto_enumTypes[1].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_inventory_service_v1_inventory_service_proto_enumTypes[1]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{1}
}

type InventoryStatus int32

const (
	InventoryStatus_INVENTORY_STATUS_UNSPECIFIED  InventoryStatus = 0
	InventoryStatus_INVENTORY_STATUS_IN_STOCK     InventoryStatus = 1
	InventoryStatus_INVENTORY_STATUS_LOW_STOCK    InventoryStatus = 2
	InventoryStatus_INVENTORY_STATUS_OUT_OF_STOCK InventoryStatus = 3
	InventoryStatus_INVENTORY_STATUS_RESERVED     InventoryStatus = 4
)

// Enum value maps for InventoryStatus.
var (
	InventoryStatus_name = map[int32]string{
		0: "INVENTORY_STATUS_UNSPECIFIED",
		1: "INVENTORY_STATUS_IN_STOCK",
		2: "INVENTORY_STATUS_LOW_STOCK",
		3: "INVENTORY_STATUS_OUT_OF_STOCK",
		4: "INVENTORY_STATUS_RESERVED",
	}
	InventoryStatus_value = map[string]int32{
		"INVENTORY_STATUS_UNSPECIFIED":  0,
		"INVENTORY_STATUS_IN_STOCK":     1,
		"INVENTORY_STATUS_LOW_STOCK":    2,
		"INVENTORY_STATUS_OUT_OF_STOCK": 3,
		"INVENTORY_STATUS_RESERVED":     4,
	}
)

func (x InventoryStatus) Enum() *InventoryStatus {
	p := new(InventoryStatus)
	*p = x
	return p
}

func (x InventoryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InventoryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_service_v1_inventory_service_proto_enumTypes[2].Descriptor()
}

func (InventoryStatus) Type() protoreflect.EnumType {
	return &file_inventory_service_v1_inventory_service_proto_enumTypes[2]
}

func (x InventoryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InventoryStatus.Descriptor instead.
func (InventoryStatus) EnumDescriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{2}
}

type Inventory struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId         string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariationId       string                 `protobuf:"bytes,3,opt,name=variation_id,json=variationId,proto3" json:"variation_id,omitempty"`
	ShopId            string                 `protobuf:"bytes,4,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Quantity          int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ReservedQuantity  int32                  `protobuf:"varint,6,opt,name=reserved_quantity,json=reservedQuantity,proto3" json:"reserved_quantity,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,7,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	AlertThreshold    int32                  `protobuf:"varint,8,opt,name=alert_threshold,json=alertThreshold,proto3" json:"alert_threshold,omitempty"`
	LastAlertedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_alerted_at,json=lastAlertedAt,proto3" json:"last_alerted_at,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{0}
}

func (x *Inventory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Inventory) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Inventory) GetVariationId() string {
	if x != nil {
		return x.VariationId
	}
	return ""
}

func (x *Inventory) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *Inventory) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Inventory) GetReservedQuantity() int32 {
	if x != nil {
		return x.ReservedQuantity
	}
	return 0
}

func (x *Inventory) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *Inventory) GetAlertThreshold() int32 {
	if x != nil {
		return x.AlertThreshold
	}
	return 0
}

func (x *Inventory) GetLastAlertedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAlertedAt
	}
	return nil
}

func (x *Inventory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Inventory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InventoryId   string                 `protobuf:"bytes,2,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Status        ReservationStatus      `protobuf:"varint,5,opt,name=status,proto3,enum=inventory_service.v1.ReservationStatus" json:"status,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ConfirmedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{1}
}

func (x *Reservation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reservation) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

func (x *Reservation) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Reservation) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Reservation) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

func (x *Reservation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Reservation) GetConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

func (x *Reservation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Reservation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type InventoryHistory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InventoryId    string                 `protobuf:"bytes,2,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	ChangeType     ChangeType             `protobuf:"varint,3,opt,name=change_type,json=changeType,proto3,enum=inventory_service.v1.ChangeType" json:"change_type,omitempty"`
	ChangeQuantity int32                  `protobuf:"varint,4,opt,name=change_quantity,json=changeQuantity,proto3" json:"change_quantity,omitempty"`
	QuantityBefore int32                  `protobuf:"varint,5,opt,name=quantity_before,json=quantityBefore,proto3" json:"quantity_before,omitempty"`
	QuantityAfter  int32                  `protobuf:"varint,6,opt,name=quantity_after,json=quantityAfter,proto3" json:"quantity_after,omitempty"`
	Reason         string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	Operator       string                 `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`
	OrderId        string                 `protobuf:"bytes,9,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InventoryHistory) Reset() {
	*x = InventoryHistory{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryHistory) ProtoMessage() {}

func (x *InventoryHistory) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryHistory.ProtoReflect.Descriptor instead.
func (*InventoryHistory) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InventoryHistory) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

func (x *InventoryHistory) GetChangeType() ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *InventoryHistory) GetChangeQuantity() int32 {
	if x != nil {
		return x.ChangeQuantity
	}
	return 0
}

func (x *InventoryHistory) GetQuantityBefore() int32 {
	if x != nil {
		return x.QuantityBefore
	}
	return 0
}

func (x *InventoryHistory) GetQuantityAfter() int32 {
	if x != nil {
		return x.QuantityAfter
	}
	return 0
}

func (x *InventoryHistory) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InventoryHistory) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *InventoryHistory) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *InventoryHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type StockTaking struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InventoryId      string                 `protobuf:"bytes,2,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	ShopId           string                 `protobuf:"bytes,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	SystemQuantity   int32                  `protobuf:"varint,4,opt,name=system_quantity,json=systemQuantity,proto3" json:"system_quantity,omitempty"`
	ActualQuantity   int32                  `protobuf:"varint,5,opt,name=actual_quantity,json=actualQuantity,proto3" json:"actual_quantity,omitempty"`
	Difference       int32                  `protobuf:"varint,6,opt,name=difference,proto3" json:"difference,omitempty"`
	DifferenceReason string                 `protobuf:"bytes,7,opt,name=difference_reason,json=differenceReason,proto3" json:"difference_reason,omitempty"`
	Operator         string                 `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StockTaking) Reset() {
	*x = StockTaking{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockTaking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockTaking) ProtoMessage() {}

func (x *StockTaking) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockTaking.ProtoReflect.Descriptor instead.
func (*StockTaking) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{3}
}

func (x *StockTaking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StockTaking) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

func (x *StockTaking) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *StockTaking) GetSystemQuantity() int32 {
	if x != nil {
		return x.SystemQuantity
	}
	return 0
}

func (x *StockTaking) GetActualQuantity() int32 {
	if x != nil {
		return x.ActualQuantity
	}
	return 0
}

func (x *StockTaking) GetDifference() int32 {
	if x != nil {
		return x.Difference
	}
	return 0
}

func (x *StockTaking) GetDifferenceReason() string {
	if x != nil {
		return x.DifferenceReason
	}
	return ""
}

func (x *StockTaking) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *StockTaking) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InventoryId   string                 `protobuf:"bytes,1,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationRequest) Reset() {
	*x = ReservationRequest{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationRequest) ProtoMessage() {}

func (x *ReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationRequest.ProtoReflect.Descriptor instead.
func (*ReservationRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReservationRequest) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

func (x *ReservationRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Request messages
type RegisterInventoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProductId       string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariationId     string                 `protobuf:"bytes,2,opt,name=variation_id,json=variationId,proto3" json:"variation_id,omitempty"`
	ShopId          string                 `protobuf:"bytes,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	InitialQuantity int32                  `protobuf:"varint,4,opt,name=initial_quantity,json=initialQuantity,proto3" json:"initial_quantity,omitempty"`
	AlertThreshold  int32                  `protobuf:"varint,5,opt,name=alert_threshold,json=alertThreshold,proto3" json:"alert_threshold,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterInventoryRequest) Reset() {
	*x = RegisterInventoryRequest{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInventoryRequest) ProtoMessage() {}

func (x *RegisterInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInventoryRequest.ProtoReflect.Descriptor instead.
func (*RegisterInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterInventoryRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *RegisterInventoryRequest) GetVariationId() string {
	if x != nil {
		return x.VariationId
	}
	return ""
}

func (x *RegisterInventoryRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *RegisterInventoryRequest) GetInitialQuantity() int32 {
	if x != nil {
		return x.InitialQuantity
	}
	return 0
}

func (x *RegisterInventoryRequest) GetAlertThreshold() int32 {
	if x != nil {
		return x.AlertThreshold
	}
	return 0
}

type UpdateInventoryQuantityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InventoryId    string                 `protobuf:"bytes,1,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	ShopId         string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	ChangeQuantity int32                  `protobuf:"varint,3,opt,name=change_quantity,json=changeQuantity,proto3" json:"change_quantity,omitempty"`
	ChangeType     ChangeType             `protobuf:"varint,4,opt,name=change_type,json=changeType,proto3,enum=inventory_service.v1.ChangeType" json:"change_type,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Operator       string                 `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateInventoryQuantityRequest) Reset() {
	*x = UpdateInventoryQuantityRequest{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryQuantityRequest) ProtoMessage() {}

func (x *UpdateInventoryQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryQuantityRequest.ProtoReflect.Descriptor instead.
func (*UpdateInventoryQuantityRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateInventoryQuantityRequest) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

func (x *UpdateInventoryQuantityRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *UpdateInventoryQuantityRequest) GetChangeQuantity() int32 {
	if x != nil {
		return x.ChangeQuantity
	}
	return 0
}

func (x *UpdateInventoryQuantityRequest) GetChangeType() ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *UpdateInventoryQuantityRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateInventoryQuantityRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InventoryId   string                 `protobuf:"bytes,1,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetInventoryRequest) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

type GetInventoryByProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariationId   string                 `protobuf:"bytes,2,opt,name=variation_id,json=variationId,proto3" json:"variation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryByProductRequest) Reset() {
	*x = GetInventoryByProductRequest{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryByProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryByProductRequest) ProtoMessage() {}

func (x *GetInventoryByProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryByProductRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryByProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetInventoryByProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetInventoryByProductRequest) GetVariationId() string {
	if x != nil {
		return x.VariationId
	}
	return ""
}

type BulkGetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []string               `protobuf:"bytes,1,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkGetInventoryRequest) Reset() {
	*x = BulkGetInventoryRequest{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkGetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkGetInventoryRequest) ProtoMessage() {}

func (x *BulkGetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkGetInventoryRequest.ProtoReflect.Descriptor instead.
func (*BulkGetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{9}
}

func (x *BulkGetInventoryRequest) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type ReserveStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InventoryId   string                 `protobuf:"bytes,1,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{10}
}

func (x *ReserveStockRequest) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

func (x *ReserveStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BulkReserveStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*ReservationRequest  `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkReserveStockRequest) Reset() {
	*x = BulkReserveStockRequest{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkReserveStockRequest) ProtoMessage() {}

func (x *BulkReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkReserveStockRequest.ProtoReflect.Descriptor instead.
func (*BulkReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{11}
}

func (x *BulkReserveStockRequest) GetReservations() []*ReservationRequest {
	if x != nil {
		return x.Reservations
	}
	return nil
}

func (x *BulkReserveStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ReleaseStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockRequest) Reset() {
	*x = ReleaseStockRequest{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockRequest) ProtoMessage() {}

func (x *ReleaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{12}
}

func (x *ReleaseStockRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ConfirmStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmStockRequest) Reset() {
	*x = ConfirmStockRequest{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmStockRequest) ProtoMessage() {}

func (x *ConfirmStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmStockRequest.ProtoReflect.Descriptor instead.
func (*ConfirmStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{13}
}

func (x *ConfirmStockRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ConfirmStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ReleaseExpiredReservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseExpiredReservationsRequest) Reset() {
	*x = ReleaseExpiredReservationsRequest{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseExpiredReservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseExpiredReservationsRequest) ProtoMessage() {}

func (x *ReleaseExpiredReservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseExpiredReservationsRequest.ProtoReflect.Descriptor instead.
func (*ReleaseExpiredReservationsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{14}
}

type CheckStockAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InventoryId   string                 `protobuf:"bytes,1,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockAlertRequest) Reset() {
	*x = CheckStockAlertRequest{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockAlertRequest) ProtoMessage() {}

func (x *CheckStockAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockAlertRequest.ProtoReflect.Descriptor instead.
func (*CheckStockAlertRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{15}
}

func (x *CheckStockAlertRequest) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

type GetInventoryHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InventoryId   string                 `protobuf:"bytes,1,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	DateFrom      string                 `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"` // YYYY-MM-DD format
	DateTo        string                 `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`       // YYYY-MM-DD format
	ChangeTypes   []ChangeType           `protobuf:"varint,4,rep,packed,name=change_types,json=changeTypes,proto3,enum=inventory_service.v1.ChangeType" json:"change_types,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryHistoryRequest) Reset() {
	*x = GetInventoryHistoryRequest{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryHistoryRequest) ProtoMessage() {}

func (x *GetInventoryHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryHistoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetInventoryHistoryRequest) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

func (x *GetInventoryHistoryRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetInventoryHistoryRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *GetInventoryHistoryRequest) GetChangeTypes() []ChangeType {
	if x != nil {
		return x.ChangeTypes
	}
	return nil
}

func (x *GetInventoryHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetInventoryHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RecordStockTakingRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InventoryId      string                 `protobuf:"bytes,1,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	ShopId           string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	ActualQuantity   int32                  `protobuf:"varint,3,opt,name=actual_quantity,json=actualQuantity,proto3" json:"actual_quantity,omitempty"`
	DifferenceReason string                 `protobuf:"bytes,4,opt,name=difference_reason,json=differenceReason,proto3" json:"difference_reason,omitempty"`
	Operator         string                 `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecordStockTakingRequest) Reset() {
	*x = RecordStockTakingRequest{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordStockTakingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordStockTakingRequest) ProtoMessage() {}

func (x *RecordStockTakingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordStockTakingRequest.ProtoReflect.Descriptor instead.
func (*RecordStockTakingRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{17}
}

func (x *RecordStockTakingRequest) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

func (x *RecordStockTakingRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *RecordStockTakingRequest) GetActualQuantity() int32 {
	if x != nil {
		return x.ActualQuantity
	}
	return 0
}

func (x *RecordStockTakingRequest) GetDifferenceReason() string {
	if x != nil {
		return x.DifferenceReason
	}
	return ""
}

func (x *RecordStockTakingRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type GetStockTakingHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	DateFrom      string                 `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"` // YYYY-MM-DD format
	DateTo        string                 `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`       // YYYY-MM-DD format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockTakingHistoryRequest) Reset() {
	*x = GetStockTakingHistoryRequest{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockTakingHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockTakingHistoryRequest) ProtoMessage() {}

func (x *GetStockTakingHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockTakingHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetStockTakingHistoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetStockTakingHistoryRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *GetStockTakingHistoryRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetStockTakingHistoryRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

// Response messages
type RegisterInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterInventoryResponse) Reset() {
	*x = RegisterInventoryResponse{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInventoryResponse) ProtoMessage() {}

func (x *RegisterInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInventoryResponse.ProtoReflect.Descriptor instead.
func (*RegisterInventoryResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterInventoryResponse) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *RegisterInventoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateInventoryQuantityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	History       *InventoryHistory      `protobuf:"bytes,2,opt,name=history,proto3" json:"history,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInventoryQuantityResponse) Reset() {
	*x = UpdateInventoryQuantityResponse{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryQuantityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryQuantityResponse) ProtoMessage() {}

func (x *UpdateInventoryQuantityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryQuantityResponse.ProtoReflect.Descriptor instead.
func (*UpdateInventoryQuantityResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateInventoryQuantityResponse) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *UpdateInventoryQuantityResponse) GetHistory() *InventoryHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *UpdateInventoryQuantityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetInventoryResponse) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type GetInventoryByProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryByProductResponse) Reset() {
	*x = GetInventoryByProductResponse{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryByProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryByProductResponse) ProtoMessage() {}

func (x *GetInventoryByProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryByProductResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryByProductResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetInventoryByProductResponse) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type BulkGetInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventories   []*Inventory           `protobuf:"bytes,1,rep,name=inventories,proto3" json:"inventories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkGetInventoryResponse) Reset() {
	*x = BulkGetInventoryResponse{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkGetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkGetInventoryResponse) ProtoMessage() {}

func (x *BulkGetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkGetInventoryResponse.ProtoReflect.Descriptor instead.
func (*BulkGetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{23}
}

func (x *BulkGetInventoryResponse) GetInventories() []*Inventory {
	if x != nil {
		return x.Inventories
	}
	return nil
}

type ReserveStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *Reservation           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockResponse) Reset() {
	*x = ReserveStockResponse{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockResponse) ProtoMessage() {}

func (x *ReserveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockResponse.ProtoReflect.Descriptor instead.
func (*ReserveStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{24}
}

func (x *ReserveStockResponse) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

func (x *ReserveStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BulkReserveStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*Reservation         `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkReserveStockResponse) Reset() {
	*x = BulkReserveStockResponse{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkReserveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkReserveStockResponse) ProtoMessage() {}

func (x *BulkReserveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkReserveStockResponse.ProtoReflect.Descriptor instead.
func (*BulkReserveStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{25}
}

func (x *BulkReserveStockResponse) GetReservations() []*Reservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

func (x *BulkReserveStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReleaseStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockResponse) Reset() {
	*x = ReleaseStockResponse{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockResponse) ProtoMessage() {}

func (x *ReleaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{26}
}

func (x *ReleaseStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfirmStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmStockResponse) Reset() {
	*x = ConfirmStockResponse{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmStockResponse) ProtoMessage() {}

func (x *ConfirmStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmStockResponse.ProtoReflect.Descriptor instead.
func (*ConfirmStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{27}
}

func (x *ConfirmStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReleaseExpiredReservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReleasedCount int32                  `protobuf:"varint,1,opt,name=released_count,json=releasedCount,proto3" json:"released_count,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseExpiredReservationsResponse) Reset() {
	*x = ReleaseExpiredReservationsResponse{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseExpiredReservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseExpiredReservationsResponse) ProtoMessage() {}

func (x *ReleaseExpiredReservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseExpiredReservationsResponse.ProtoReflect.Descriptor instead.
func (*ReleaseExpiredReservationsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{28}
}

func (x *ReleaseExpiredReservationsResponse) GetReleasedCount() int32 {
	if x != nil {
		return x.ReleasedCount
	}
	return 0
}

func (x *ReleaseExpiredReservationsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckStockAlertResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsLowStock      bool                   `protobuf:"varint,1,opt,name=is_low_stock,json=isLowStock,proto3" json:"is_low_stock,omitempty"`
	CurrentQuantity int32                  `protobuf:"varint,2,opt,name=current_quantity,json=currentQuantity,proto3" json:"current_quantity,omitempty"`
	AlertThreshold  int32                  `protobuf:"varint,3,opt,name=alert_threshold,json=alertThreshold,proto3" json:"alert_threshold,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckStockAlertResponse) Reset() {
	*x = CheckStockAlertResponse{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockAlertResponse) ProtoMessage() {}

func (x *CheckStockAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockAlertResponse.ProtoReflect.Descriptor instead.
func (*CheckStockAlertResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{29}
}

func (x *CheckStockAlertResponse) GetIsLowStock() bool {
	if x != nil {
		return x.IsLowStock
	}
	return false
}

func (x *CheckStockAlertResponse) GetCurrentQuantity() int32 {
	if x != nil {
		return x.CurrentQuantity
	}
	return 0
}

func (x *CheckStockAlertResponse) GetAlertThreshold() int32 {
	if x != nil {
		return x.AlertThreshold
	}
	return 0
}

type GetInventoryHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*InventoryHistory    `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryHistoryResponse) Reset() {
	*x = GetInventoryHistoryResponse{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryHistoryResponse) ProtoMessage() {}

func (x *GetInventoryHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryHistoryResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{30}
}

func (x *GetInventoryHistoryResponse) GetHistory() []*InventoryHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *GetInventoryHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetInventoryHistoryResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetInventoryHistoryResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RecordStockTakingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockTaking   *StockTaking           `protobuf:"bytes,1,opt,name=stock_taking,json=stockTaking,proto3" json:"stock_taking,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordStockTakingResponse) Reset() {
	*x = RecordStockTakingResponse{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordStockTakingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordStockTakingResponse) ProtoMessage() {}

func (x *RecordStockTakingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordStockTakingResponse.ProtoReflect.Descriptor instead.
func (*RecordStockTakingResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{31}
}

func (x *RecordStockTakingResponse) GetStockTaking() *StockTaking {
	if x != nil {
		return x.StockTaking
	}
	return nil
}

func (x *RecordStockTakingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStockTakingHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*StockTaking         `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockTakingHistoryResponse) Reset() {
	*x = GetStockTakingHistoryResponse{}
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockTakingHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockTakingHistoryResponse) ProtoMessage() {}

func (x *GetStockTakingHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_v1_inventory_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockTakingHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetStockTakingHistoryResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_v1_inventory_service_proto_rawDescGZIP(), []int{32}
}

func (x *GetStockTakingHistoryResponse) GetHistory() []*StockTaking {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *GetStockTakingHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_inventory_service_v1_inventory_service_proto protoreflect.FileDescriptor

const file_inventory_service_v1_inventory_service_proto_rawDesc = "" +
	"\n" +
	",inventory-service/v1/inventory-service.proto\x12\x14inventory_service.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x03\n" +
	"\tInventory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12!\n" +
	"\fvariation_id\x18\x03 \x01(\tR\vvariationId\x12\x17\n" +
	"\ashop_id\x18\x04 \x01(\tR\x06shopId\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12+\n" +
	"\x11reserved_quantity\x18\x06 \x01(\x05R\x10reservedQuantity\x12-\n" +
	"\x12available_quantity\x18\a \x01(\x05R\x11availableQuantity\x12'\n" +
	"\x0falert_threshold\x18\b \x01(\x05R\x0ealertThreshold\x12B\n" +
	"\x0flast_alerted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rlastAlertedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa8\x03\n" +
	"\vReservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\finventory_id\x18\x02 \x01(\tR\vinventoryId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12?\n" +
	"\x06status\x18\x05 \x01(\x0e2'.inventory_service.v1.ReservationStatusR\x06status\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12=\n" +
	"\fconfirmed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmedAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8b\x03\n" +
	"\x10InventoryHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\finventory_id\x18\x02 \x01(\tR\vinventoryId\x12A\n" +
	"\vchange_type\x18\x03 \x01(\x0e2 .inventory_service.v1.ChangeTypeR\n" +
	"changeType\x12'\n" +
	"\x0fchange_quantity\x18\x04 \x01(\x05R\x0echangeQuantity\x12'\n" +
	"\x0fquantity_before\x18\x05 \x01(\x05R\x0equantityBefore\x12%\n" +
	"\x0equantity_after\x18\x06 \x01(\x05R\rquantityAfter\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x1a\n" +
	"\boperator\x18\b \x01(\tR\boperator\x12\x19\n" +
	"\border_id\x18\t \x01(\tR\aorderId\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xcf\x02\n" +
	"\vStockTaking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\finventory_id\x18\x02 \x01(\tR\vinventoryId\x12\x17\n" +
	"\ashop_id\x18\x03 \x01(\tR\x06shopId\x12'\n" +
	"\x0fsystem_quantity\x18\x04 \x01(\x05R\x0esystemQuantity\x12'\n" +
	"\x0factual_quantity\x18\x05 \x01(\x05R\x0eactualQuantity\x12\x1e\n" +
	"\n" +
	"difference\x18\x06 \x01(\x05R\n" +
	"difference\x12+\n" +
	"\x11difference_reason\x18\a \x01(\tR\x10differenceReason\x12\x1a\n" +
	"\boperator\x18\b \x01(\tR\boperator\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"S\n" +
	"\x12ReservationRequest\x12!\n" +
	"\finventory_id\x18\x01 \x01(\tR\vinventoryId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\xc9\x01\n" +
	"\x18RegisterInventoryRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fvariation_id\x18\x02 \x01(\tR\vvariationId\x12\x17\n" +
	"\ashop_id\x18\x03 \x01(\tR\x06shopId\x12)\n" +
	"\x10initial_quantity\x18\x04 \x01(\x05R\x0finitialQuantity\x12'\n" +
	"\x0falert_threshold\x18\x05 \x01(\x05R\x0ealertThreshold\"\xfc\x01\n" +
	"\x1eUpdateInventoryQuantityRequest\x12!\n" +
	"\finventory_id\x18\x01 \x01(\tR\vinventoryId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12'\n" +
	"\x0fchange_quantity\x18\x03 \x01(\x05R\x0echangeQuantity\x12A\n" +
	"\vchange_type\x18\x04 \x01(\x0e2 .inventory_service.v1.ChangeTypeR\n" +
	"changeType\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1a\n" +
	"\boperator\x18\x06 \x01(\tR\boperator\"8\n" +
	"\x13GetInventoryRequest\x12!\n" +
	"\finventory_id\x18\x01 \x01(\tR\vinventoryId\"`\n" +
	"\x1cGetInventoryByProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fvariation_id\x18\x02 \x01(\tR\vvariationId\":\n" +
	"\x17BulkGetInventoryRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\tR\n" +
	"productIds\"o\n" +
	"\x13ReserveStockRequest\x12!\n" +
	"\finventory_id\x18\x01 \x01(\tR\vinventoryId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\x82\x01\n" +
	"\x17BulkReserveStockRequest\x12L\n" +
	"\freservations\x18\x01 \x03(\v2(.inventory_service.v1.ReservationRequestR\freservations\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"W\n" +
	"\x13ReleaseStockRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"W\n" +
	"\x13ConfirmStockRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"#\n" +
	"!ReleaseExpiredReservationsRequest\";\n" +
	"\x16CheckStockAlertRequest\x12!\n" +
	"\finventory_id\x18\x01 \x01(\tR\vinventoryId\"\xeb\x01\n" +
	"\x1aGetInventoryHistoryRequest\x12!\n" +
	"\finventory_id\x18\x01 \x01(\tR\vinventoryId\x12\x1b\n" +
	"\tdate_from\x18\x02 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x03 \x01(\tR\x06dateTo\x12C\n" +
	"\fchange_types\x18\x04 \x03(\x0e2 .inventory_service.v1.ChangeTypeR\vchangeTypes\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\xc8\x01\n" +
	"\x18RecordStockTakingRequest\x12!\n" +
	"\finventory_id\x18\x01 \x01(\tR\vinventoryId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12'\n" +
	"\x0factual_quantity\x18\x03 \x01(\x05R\x0eactualQuantity\x12+\n" +
	"\x11difference_reason\x18\x04 \x01(\tR\x10differenceReason\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\"m\n" +
	"\x1cGetStockTakingHistoryRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12\x1b\n" +
	"\tdate_from\x18\x02 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x03 \x01(\tR\x06dateTo\"t\n" +
	"\x19RegisterInventoryResponse\x12=\n" +
	"\tinventory\x18\x01 \x01(\v2\x1f.inventory_service.v1.InventoryR\tinventory\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbc\x01\n" +
	"\x1fUpdateInventoryQuantityResponse\x12=\n" +
	"\tinventory\x18\x01 \x01(\v2\x1f.inventory_service.v1.InventoryR\tinventory\x12@\n" +
	"\ahistory\x18\x02 \x01(\v2&.inventory_service.v1.InventoryHistoryR\ahistory\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"U\n" +
	"\x14GetInventoryResponse\x12=\n" +
	"\tinventory\x18\x01 \x01(\v2\x1f.inventory_service.v1.InventoryR\tinventory\"^\n" +
	"\x1dGetInventoryByProductResponse\x12=\n" +
	"\tinventory\x18\x01 \x01(\v2\x1f.inventory_service.v1.InventoryR\tinventory\"]\n" +
	"\x18BulkGetInventoryResponse\x12A\n" +
	"\vinventories\x18\x01 \x03(\v2\x1f.inventory_service.v1.InventoryR\vinventories\"u\n" +
	"\x14ReserveStockResponse\x12C\n" +
	"\vreservation\x18\x01 \x01(\v2!.inventory_service.v1.ReservationR\vreservation\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"{\n" +
	"\x18BulkReserveStockResponse\x12E\n" +
	"\freservations\x18\x01 \x03(\v2!.inventory_service.v1.ReservationR\freservations\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\x14ReleaseStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\x14ConfirmStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"e\n" +
	"\"ReleaseExpiredReservationsResponse\x12%\n" +
	"\x0ereleased_count\x18\x01 \x01(\x05R\rreleasedCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8f\x01\n" +
	"\x17CheckStockAlertResponse\x12 \n" +
	"\fis_low_stock\x18\x01 \x01(\bR\n" +
	"isLowStock\x12)\n" +
	"\x10current_quantity\x18\x02 \x01(\x05R\x0fcurrentQuantity\x12'\n" +
	"\x0falert_threshold\x18\x03 \x01(\x05R\x0ealertThreshold\"\xb1\x01\n" +
	"\x1bGetInventoryHistoryResponse\x12@\n" +
	"\ahistory\x18\x01 \x03(\v2&.inventory_service.v1.InventoryHistoryR\ahistory\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"{\n" +
	"\x19RecordStockTakingResponse\x12D\n" +
	"\fstock_taking\x18\x01 \x01(\v2!.inventory_service.v1.StockTakingR\vstockTaking\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"}\n" +
	"\x1dGetStockTakingHistoryResponse\x12;\n" +
	"\ahistory\x18\x01 \x03(\v2!.inventory_service.v1.StockTakingR\ahistory\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount*\xbb\x01\n" +
	"\x11ReservationStatus\x12\"\n" +
	"\x1eRESERVATION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bRESERVATION_STATUS_RESERVED\x10\x01\x12 \n" +
	"\x1cRESERVATION_STATUS_CONFIRMED\x10\x02\x12\x1f\n" +
	"\x1bRESERVATION_STATUS_RELEASED\x10\x03\x12\x1e\n" +
	"\x1aRESERVATION_STATUS_EXPIRED\x10\x04*\xa0\x02\n" +
	"\n" +
	"ChangeType\x12\x1b\n" +
	"\x17CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CHANGE_TYPE_INITIAL\x10\x01\x12\x17\n" +
	"\x13CHANGE_TYPE_RESTOCK\x10\x02\x12\x16\n" +
	"\x12CHANGE_TYPE_RETURN\x10\x03\x12\x1b\n" +
	"\x17CHANGE_TYPE_RESERVATION\x10\x04\x12\x17\n" +
	"\x13CHANGE_TYPE_RELEASE\x10\x05\x12\x1c\n" +
	"\x18CHANGE_TYPE_CONFIRMATION\x10\x06\x12\x16\n" +
	"\x12CHANGE_TYPE_DAMAGE\x10\a\x12\x1c\n" +
	"\x18CHANGE_TYPE_STOCK_TAKING\x10\b\x12!\n" +
	"\x1dCHANGE_TYPE_MANUAL_ADJUSTMENT\x10\t*\xb4\x01\n" +
	"\x0fInventoryStatus\x12 \n" +
	"\x1cINVENTORY_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19INVENTORY_STATUS_IN_STOCK\x10\x01\x12\x1e\n" +
	"\x1aINVENTORY_STATUS_LOW_STOCK\x10\x02\x12!\n" +
	"\x1dINVENTORY_STATUS_OUT_OF_STOCK\x10\x03\x12\x1d\n" +
	"\x19INVENTORY_STATUS_RESERVED\x10\x042\x8d\r\n" +
	"\x10InventoryService\x12t\n" +
	"\x11RegisterInventory\x12..inventory_service.v1.RegisterInventoryRequest\x1a/.inventory_service.v1.RegisterInventoryResponse\x12\x86\x01\n" +
	"\x17UpdateInventoryQuantity\x124.inventory_service.v1.UpdateInventoryQuantityRequest\x1a5.inventory_service.v1.UpdateInventoryQuantityResponse\x12e\n" +
	"\fGetInventory\x12).inventory_service.v1.GetInventoryRequest\x1a*.inventory_service.v1.GetInventoryResponse\x12\x80\x01\n" +
	"\x15GetInventoryByProduct\x122.inventory_service.v1.GetInventoryByProductRequest\x1a3.inventory_service.v1.GetInventoryByProductResponse\x12q\n" +
	"\x10BulkGetInventory\x12-.inventory_service.v1.BulkGetInventoryRequest\x1a..inventory_service.v1.BulkGetInventoryResponse\x12e\n" +
	"\fReserveStock\x12).inventory_service.v1.ReserveStockRequest\x1a*.inventory_service.v1.ReserveStockResponse\x12q\n" +
	"\x10BulkReserveStock\x12-.inventory_service.v1.BulkReserveStockRequest\x1a..inventory_service.v1.BulkReserveStockResponse\x12e\n" +
	"\fReleaseStock\x12).inventory_service.v1.ReleaseStockRequest\x1a*.inventory_service.v1.ReleaseStockResponse\x12e\n" +
	"\fConfirmStock\x12).inventory_service.v1.ConfirmStockRequest\x1a*.inventory_service.v1.ConfirmStockResponse\x12\x8f\x01\n" +
	"\x1aReleaseExpiredReservations\x127.inventory_service.v1.ReleaseExpiredReservationsRequest\x1a8.inventory_service.v1.ReleaseExpiredReservationsResponse\x12n\n" +
	"\x0fCheckStockAlert\x12,.inventory_service.v1.CheckStockAlertRequest\x1a-.inventory_service.v1.CheckStockAlertResponse\x12z\n" +
	"\x13GetInventoryHistory\x120.inventory_service.v1.GetInventoryHistoryRequest\x1a1.inventory_service.v1.GetInventoryHistoryResponse\x12t\n" +
	"\x11RecordStockTaking\x12..inventory_service.v1.RecordStockTakingRequest\x1a/.inventory_service.v1.RecordStockTakingResponse\x12\x80\x01\n" +
	"\x15GetStockTakingHistory\x122.inventory_service.v1.GetStockTakingHistoryRequest\x1a3.inventory_service.v1.GetStockTakingHistoryResponseBPZNgithub.com/makoto-developer/go_microservice_example/proto/inventory_service/v1b\x06proto3"

var (
	file_inventory_service_v1_inventory_service_proto_rawDescOnce sync.Once
	file_inventory_service_v1_inventory_service_proto_rawDescData []byte
)

func file_inventory_service_v1_inventory_service_proto_rawDescGZIP() []byte {
	file_inventory_service_v1_inventory_service_proto_rawDescOnce.Do(func() {
		file_inventory_service_v1_inventory_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_service_v1_inventory_service_proto_rawDesc), len(file_inventory_service_v1_inventory_service_proto_rawDesc)))
	})
	return file_inventory_service_v1_inventory_service_proto_rawDescData
}

var file_inventory_service_v1_inventory_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_inventory_service_v1_inventory_service_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_inventory_service_v1_inventory_service_proto_goTypes = []any{
	(ReservationStatus)(0),                     // 0: inventory_service.v1.ReservationStatus
	(ChangeType)(0),                            // 1: inventory_service.v1.ChangeType
	(InventoryStatus)(0),                       // 2: inventory_service.v1.InventoryStatus
	(*Inventory)(nil),                          // 3: inventory_service.v1.Inventory
	(*Reservation)(nil),                        // 4: inventory_service.v1.Reservation
	(*InventoryHistory)(nil),                   // 5: inventory_service.v1.InventoryHistory
	(*StockTaking)(nil),                        // 6: inventory_service.v1.StockTaking
	(*ReservationRequest)(nil),                 // 7: inventory_service.v1.ReservationRequest
	(*RegisterInventoryRequest)(nil),           // 8: inventory_service.v1.RegisterInventoryRequest
	(*UpdateInventoryQuantityRequest)(nil),     // 9: inventory_service.v1.UpdateInventoryQuantityRequest
	(*GetInventoryRequest)(nil),                // 10: inventory_service.v1.GetInventoryRequest
	(*GetInventoryByProductRequest)(nil),       // 11: inventory_service.v1.GetInventoryByProductRequest
	(*BulkGetInventoryRequest)(nil),            // 12: inventory_service.v1.BulkGetInventoryRequest
	(*ReserveStockRequest)(nil),                // 13: inventory_service.v1.ReserveStockRequest
	(*BulkReserveStockRequest)(nil),            // 14: inventory_service.v1.BulkReserveStockRequest
	(*ReleaseStockRequest)(nil),                // 15: inventory_service.v1.ReleaseStockRequest
	(*ConfirmStockRequest)(nil),                // 16: inventory_service.v1.ConfirmStockRequest
	(*ReleaseExpiredReservationsRequest)(nil),  // 17: inventory_service.v1.ReleaseExpiredReservationsRequest
	(*CheckStockAlertRequest)(nil),             // 18: inventory_service.v1.CheckStockAlertRequest
	(*GetInventoryHistoryRequest)(nil),         // 19: inventory_service.v1.GetInventoryHistoryRequest
	(*RecordStockTakingRequest)(nil),           // 20: inventory_service.v1.RecordStockTakingRequest
	(*GetStockTakingHistoryRequest)(nil),       // 21: inventory_service.v1.GetStockTakingHistoryRequest
	(*RegisterInventoryResponse)(nil),          // 22: inventory_service.v1.RegisterInventoryResponse
	(*UpdateInventoryQuantityResponse)(nil),    // 23: inventory_service.v1.UpdateInventoryQuantityResponse
	(*GetInventoryResponse)(nil),               // 24: inventory_service.v1.GetInventoryResponse
	(*GetInventoryByProductResponse)(nil),      // 25: inventory_service.v1.GetInventoryByProductResponse
	(*BulkGetInventoryResponse)(nil),           // 26: inventory_service.v1.BulkGetInventoryResponse
	(*ReserveStockResponse)(nil),               // 27: inventory_service.v1.ReserveStockResponse
	(*BulkReserveStockResponse)(nil),           // 28: inventory_service.v1.BulkReserveStockResponse
	(*ReleaseStockResponse)(nil),               // 29: inventory_service.v1.ReleaseStockResponse
	(*ConfirmStockResponse)(nil),               // 30: inventory_service.v1.ConfirmStockResponse
	(*ReleaseExpiredReservationsResponse)(nil), // 31: inventory_service.v1.ReleaseExpiredReservationsResponse
	(*CheckStockAlertResponse)(nil),            // 32: inventory_service.v1.CheckStockAlertResponse
	(*GetInventoryHistoryResponse)(nil),        // 33: inventory_service.v1.GetInventoryHistoryResponse
	(*RecordStockTakingResponse)(nil),          // 34: inventory_service.v1.RecordStockTakingResponse
	(*GetStockTakingHistoryResponse)(nil),      // 35: inventory_service.v1.GetStockTakingHistoryResponse
	(*timestamppb.Timestamp)(nil),              // 36: google.protobuf.Timestamp
}
var file_inventory_service_v1_inventory_service_proto_depIdxs = []int32{
	36, // 0: inventory_service.v1.Inventory.last_alerted_at:type_name -> google.protobuf.Timestamp
	36, // 1: inventory_service.v1.Inventory.created_at:type_name -> google.protobuf.Timestamp
	36, // 2: inventory_service.v1.Inventory.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: inventory_service.v1.Reservation.status:type_name -> inventory_service.v1.ReservationStatus
	36, // 4: inventory_service.v1.Reservation.expires_at:type_name -> google.protobuf.Timestamp
	36, // 5: inventory_service.v1.Reservation.confirmed_at:type_name -> google.protobuf.Timestamp
	36, // 6: inventory_service.v1.Reservation.created_at:type_name -> google.protobuf.Timestamp
	36, // 7: inventory_service.v1.Reservation.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 8: inventory_service.v1.InventoryHistory.change_type:type_name -> inventory_service.v1.ChangeType
	36, // 9: inventory_service.v1.InventoryHistory.created_at:type_name -> google.protobuf.Timestamp
	36, // 10: inventory_service.v1.StockTaking.created_at:type_name -> google.protobuf.Timestamp
	1,  // 11: inventory_service.v1.UpdateInventoryQuantityRequest.change_type:type_name -> inventory_service.v1.ChangeType
	7,  // 12: inventory_service.v1.BulkReserveStockRequest.reservations:type_name -> inventory_service.v1.ReservationRequest
	1,  // 13: inventory_service.v1.GetInventoryHistoryRequest.change_types:type_name -> inventory_service.v1.ChangeType
	3,  // 14: inventory_service.v1.RegisterInventoryResponse.inventory:type_name -> inventory_service.v1.Inventory
	3,  // 15: inventory_service.v1.UpdateInventoryQuantityResponse.inventory:type_name -> inventory_service.v1.Inventory
	5,  // 16: inventory_service.v1.UpdateInventoryQuantityResponse.history:type_name -> inventory_service.v1.InventoryHistory
	3,  // 17: inventory_service.v1.GetInventoryResponse.inventory:type_name -> inventory_service.v1.Inventory
	3,  // 18: inventory_service.v1.GetInventoryByProductResponse.inventory:type_name -> inventory_service.v1.Inventory
	3,  // 19: inventory_service.v1.BulkGetInventoryResponse.inventories:type_name -> inventory_service.v1.Inventory
	4,  // 20: inventory_service.v1.ReserveStockResponse.reservation:type_name -> inventory_service.v1.Reservation
	4,  // 21: inventory_service.v1.BulkReserveStockResponse.reservations:type_name -> inventory_service.v1.Reservation
	5,  // 22: inventory_service.v1.GetInventoryHistoryResponse.history:type_name -> inventory_service.v1.InventoryHistory
	6,  // 23: inventory_service.v1.RecordStockTakingResponse.stock_taking:type_name -> inventory_service.v1.StockTaking
	6,  // 24: inventory_service.v1.GetStockTakingHistoryResponse.history:type_name -> inventory_service.v1.StockTaking
	8,  // 25: inventory_service.v1.InventoryService.RegisterInventory:input_type -> inventory_service.v1.RegisterInventoryRequest
	9,  // 26: inventory_service.v1.InventoryService.UpdateInventoryQuantity:input_type -> inventory_service.v1.UpdateInventoryQuantityRequest
	10, // 27: inventory_service.v1.InventoryService.GetInventory:input_type -> inventory_service.v1.GetInventoryRequest
	11, // 28: inventory_service.v1.InventoryService.GetInventoryByProduct:input_type -> inventory_service.v1.GetInventoryByProductRequest
	12, // 29: inventory_service.v1.InventoryService.BulkGetInventory:input_type -> inventory_service.v1.BulkGetInventoryRequest
	13, // 30: inventory_service.v1.InventoryService.ReserveStock:input_type -> inventory_service.v1.ReserveStockRequest
	14, // 31: inventory_service.v1.InventoryService.BulkReserveStock:input_type -> inventory_service.v1.BulkReserveStockRequest
	15, // 32: inventory_service.v1.InventoryService.ReleaseStock:input_type -> inventory_service.v1.ReleaseStockRequest
	16, // 33: inventory_service.v1.InventoryService.ConfirmStock:input_type -> inventory_service.v1.ConfirmStockRequest
	17, // 34: inventory_service.v1.InventoryService.ReleaseExpiredReservations:input_type -> inventory_service.v1.ReleaseExpiredReservationsRequest
	18, // 35: inventory_service.v1.InventoryService.CheckStockAlert:input_type -> inventory_service.v1.CheckStockAlertRequest
	19, // 36: inventory_service.v1.InventoryService.GetInventoryHistory:input_type -> inventory_service.v1.GetInventoryHistoryRequest
	20, // 37: inventory_service.v1.InventoryService.RecordStockTaking:input_type -> inventory_service.v1.RecordStockTakingRequest
	21, // 38: inventory_service.v1.InventoryService.GetStockTakingHistory:input_type -> inventory_service.v1.GetStockTakingHistoryRequest
	22, // 39: inventory_service.v1.InventoryService.RegisterInventory:output_type -> inventory_service.v1.RegisterInventoryResponse
	23, // 40: inventory_service.v1.InventoryService.UpdateInventoryQuantity:output_type -> inventory_service.v1.UpdateInventoryQuantityResponse
	24, // 41: inventory_service.v1.InventoryService.GetInventory:output_type -> inventory_service.v1.GetInventoryResponse
	25, // 42: inventory_service.v1.InventoryService.GetInventoryByProduct:output_type -> inventory_service.v1.GetInventoryByProductResponse
	26, // 43: inventory_service.v1.InventoryService.BulkGetInventory:output_type -> inventory_service.v1.BulkGetInventoryResponse
	27, // 44: inventory_service.v1.InventoryService.ReserveStock:output_type -> inventory_service.v1.ReserveStockResponse
	28, // 45: inventory_service.v1.InventoryService.BulkReserveStock:output_type -> inventory_service.v1.BulkReserveStockResponse
	29, // 46: inventory_service.v1.InventoryService.ReleaseStock:output_type -> inventory_service.v1.ReleaseStockResponse
	30, // 47: inventory_service.v1.InventoryService.ConfirmStock:output_type -> inventory_service.v1.ConfirmStockResponse
	31, // 48: inventory_service.v1.InventoryService.ReleaseExpiredReservations:output_type -> inventory_service.v1.ReleaseExpiredReservationsResponse
	32, // 49: inventory_service.v1.InventoryService.CheckStockAlert:output_type -> inventory_service.v1.CheckStockAlertResponse
	33, // 50: inventory_service.v1.InventoryService.GetInventoryHistory:output_type -> inventory_service.v1.GetInventoryHistoryResponse
	34, // 51: inventory_service.v1.InventoryService.RecordStockTaking:output_type -> inventory_service.v1.RecordStockTakingResponse
	35, // 52: inventory_service.v1.InventoryService.GetStockTakingHistory:output_type -> inventory_service.v1.GetStockTakingHistoryResponse
	39, // [39:53] is the sub-list for method output_type
	25, // [25:39] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_inventory_service_v1_inventory_service_proto_init() }
func file_inventory_service_v1_inventory_service_proto_init() {
	if File_inventory_service_v1_inventory_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_service_v1_inventory_service_proto_rawDesc), len(file_inventory_service_v1_inventory_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_service_v1_inventory_service_proto_goTypes,
		DependencyIndexes: file_inventory_service_v1_inventory_service_proto_depIdxs,
		EnumInfos:         file_inventory_service_v1_inventory_service_proto_enumTypes,
		MessageInfos:      file_inventory_service_v1_inventory_service_proto_msgTypes,
	}.Build()
	File_inventory_service_v1_inventory_service_proto = out.File
	file_inventory_service_v1_inventory_service_proto_goTypes = nil
	file_inventory_service_v1_inventory_service_proto_depIdxs = nil
}
