// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: customer_auth.proto

package customer_authv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustomerAuthService_Register_FullMethodName             = "/customer_auth.v1.CustomerAuthService/Register"
	CustomerAuthService_Login_FullMethodName                = "/customer_auth.v1.CustomerAuthService/Login"
	CustomerAuthService_Logout_FullMethodName               = "/customer_auth.v1.CustomerAuthService/Logout"
	CustomerAuthService_VerifyEmail_FullMethodName          = "/customer_auth.v1.CustomerAuthService/VerifyEmail"
	CustomerAuthService_RequestPasswordReset_FullMethodName = "/customer_auth.v1.CustomerAuthService/RequestPasswordReset"
	CustomerAuthService_ResetPassword_FullMethodName        = "/customer_auth.v1.CustomerAuthService/ResetPassword"
	CustomerAuthService_RefreshToken_FullMethodName         = "/customer_auth.v1.CustomerAuthService/RefreshToken"
)

// CustomerAuthServiceClient is the client API for CustomerAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CustomerAuthService handles authentication for customers
type CustomerAuthServiceClient interface {
	// Register registers a new customer
	Register(ctx context.Context, in *CustomerRegisterRequest, opts ...grpc.CallOption) (*CustomerRegisterResponse, error)
	// Login authenticates a customer
	Login(ctx context.Context, in *CustomerLoginRequest, opts ...grpc.CallOption) (*CustomerLoginResponse, error)
	// Logout logs out a customer
	Logout(ctx context.Context, in *CustomerLogoutRequest, opts ...grpc.CallOption) (*CustomerLogoutResponse, error)
	// VerifyEmail verifies customer's email address
	VerifyEmail(ctx context.Context, in *CustomerVerifyEmailRequest, opts ...grpc.CallOption) (*CustomerVerifyEmailResponse, error)
	// RequestPasswordReset initiates password reset process
	RequestPasswordReset(ctx context.Context, in *CustomerRequestPasswordResetRequest, opts ...grpc.CallOption) (*CustomerRequestPasswordResetResponse, error)
	// ResetPassword resets customer's password
	ResetPassword(ctx context.Context, in *CustomerResetPasswordRequest, opts ...grpc.CallOption) (*CustomerResetPasswordResponse, error)
	// RefreshToken refreshes access token
	RefreshToken(ctx context.Context, in *CustomerRefreshTokenRequest, opts ...grpc.CallOption) (*CustomerRefreshTokenResponse, error)
}

type customerAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerAuthServiceClient(cc grpc.ClientConnInterface) CustomerAuthServiceClient {
	return &customerAuthServiceClient{cc}
}

func (c *customerAuthServiceClient) Register(ctx context.Context, in *CustomerRegisterRequest, opts ...grpc.CallOption) (*CustomerRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomerRegisterResponse)
	err := c.cc.Invoke(ctx, CustomerAuthService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAuthServiceClient) Login(ctx context.Context, in *CustomerLoginRequest, opts ...grpc.CallOption) (*CustomerLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomerLoginResponse)
	err := c.cc.Invoke(ctx, CustomerAuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAuthServiceClient) Logout(ctx context.Context, in *CustomerLogoutRequest, opts ...grpc.CallOption) (*CustomerLogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomerLogoutResponse)
	err := c.cc.Invoke(ctx, CustomerAuthService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAuthServiceClient) VerifyEmail(ctx context.Context, in *CustomerVerifyEmailRequest, opts ...grpc.CallOption) (*CustomerVerifyEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomerVerifyEmailResponse)
	err := c.cc.Invoke(ctx, CustomerAuthService_VerifyEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAuthServiceClient) RequestPasswordReset(ctx context.Context, in *CustomerRequestPasswordResetRequest, opts ...grpc.CallOption) (*CustomerRequestPasswordResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomerRequestPasswordResetResponse)
	err := c.cc.Invoke(ctx, CustomerAuthService_RequestPasswordReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAuthServiceClient) ResetPassword(ctx context.Context, in *CustomerResetPasswordRequest, opts ...grpc.CallOption) (*CustomerResetPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomerResetPasswordResponse)
	err := c.cc.Invoke(ctx, CustomerAuthService_ResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAuthServiceClient) RefreshToken(ctx context.Context, in *CustomerRefreshTokenRequest, opts ...grpc.CallOption) (*CustomerRefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomerRefreshTokenResponse)
	err := c.cc.Invoke(ctx, CustomerAuthService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerAuthServiceServer is the server API for CustomerAuthService service.
// All implementations must embed UnimplementedCustomerAuthServiceServer
// for forward compatibility.
//
// CustomerAuthService handles authentication for customers
type CustomerAuthServiceServer interface {
	// Register registers a new customer
	Register(context.Context, *CustomerRegisterRequest) (*CustomerRegisterResponse, error)
	// Login authenticates a customer
	Login(context.Context, *CustomerLoginRequest) (*CustomerLoginResponse, error)
	// Logout logs out a customer
	Logout(context.Context, *CustomerLogoutRequest) (*CustomerLogoutResponse, error)
	// VerifyEmail verifies customer's email address
	VerifyEmail(context.Context, *CustomerVerifyEmailRequest) (*CustomerVerifyEmailResponse, error)
	// RequestPasswordReset initiates password reset process
	RequestPasswordReset(context.Context, *CustomerRequestPasswordResetRequest) (*CustomerRequestPasswordResetResponse, error)
	// ResetPassword resets customer's password
	ResetPassword(context.Context, *CustomerResetPasswordRequest) (*CustomerResetPasswordResponse, error)
	// RefreshToken refreshes access token
	RefreshToken(context.Context, *CustomerRefreshTokenRequest) (*CustomerRefreshTokenResponse, error)
	mustEmbedUnimplementedCustomerAuthServiceServer()
}

// UnimplementedCustomerAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomerAuthServiceServer struct{}

func (UnimplementedCustomerAuthServiceServer) Register(context.Context, *CustomerRegisterRequest) (*CustomerRegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedCustomerAuthServiceServer) Login(context.Context, *CustomerLoginRequest) (*CustomerLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedCustomerAuthServiceServer) Logout(context.Context, *CustomerLogoutRequest) (*CustomerLogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedCustomerAuthServiceServer) VerifyEmail(context.Context, *CustomerVerifyEmailRequest) (*CustomerVerifyEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyEmail not implemented")
}
func (UnimplementedCustomerAuthServiceServer) RequestPasswordReset(context.Context, *CustomerRequestPasswordResetRequest) (*CustomerRequestPasswordResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestPasswordReset not implemented")
}
func (UnimplementedCustomerAuthServiceServer) ResetPassword(context.Context, *CustomerResetPasswordRequest) (*CustomerResetPasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedCustomerAuthServiceServer) RefreshToken(context.Context, *CustomerRefreshTokenRequest) (*CustomerRefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedCustomerAuthServiceServer) mustEmbedUnimplementedCustomerAuthServiceServer() {}
func (UnimplementedCustomerAuthServiceServer) testEmbeddedByValue()                             {}

// UnsafeCustomerAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerAuthServiceServer will
// result in compilation errors.
type UnsafeCustomerAuthServiceServer interface {
	mustEmbedUnimplementedCustomerAuthServiceServer()
}

func RegisterCustomerAuthServiceServer(s grpc.ServiceRegistrar, srv CustomerAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedCustomerAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustomerAuthService_ServiceDesc, srv)
}

func _CustomerAuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerAuthService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAuthServiceServer).Register(ctx, req.(*CustomerRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerAuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAuthServiceServer).Login(ctx, req.(*CustomerLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerAuthService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAuthServiceServer).Logout(ctx, req.(*CustomerLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAuthService_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerVerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAuthServiceServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerAuthService_VerifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAuthServiceServer).VerifyEmail(ctx, req.(*CustomerVerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAuthService_RequestPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRequestPasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAuthServiceServer).RequestPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerAuthService_RequestPasswordReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAuthServiceServer).RequestPasswordReset(ctx, req.(*CustomerRequestPasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAuthService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAuthServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerAuthService_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAuthServiceServer).ResetPassword(ctx, req.(*CustomerResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAuthService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAuthServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerAuthService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAuthServiceServer).RefreshToken(ctx, req.(*CustomerRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerAuthService_ServiceDesc is the grpc.ServiceDesc for CustomerAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customer_auth.v1.CustomerAuthService",
	HandlerType: (*CustomerAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _CustomerAuthService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _CustomerAuthService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _CustomerAuthService_Logout_Handler,
		},
		{
			MethodName: "VerifyEmail",
			Handler:    _CustomerAuthService_VerifyEmail_Handler,
		},
		{
			MethodName: "RequestPasswordReset",
			Handler:    _CustomerAuthService_RequestPasswordReset_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _CustomerAuthService_ResetPassword_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _CustomerAuthService_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer_auth.proto",
}
