defmodule ShopMallWebWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :shop_mall_web

  # セッションはクッキーに保存する。access_token など機微な値を入れるため、
  # 署名(改竄防止)に加えて encryption_salt で暗号化し、内容を読めないようにする。
  @session_options [
    store: :cookie,
    key: "_shop_mall_web_key",
    signing_salt: "EA7W0OKm",
    encryption_salt: "kQ3mZ8vT",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :shop_mall_web,
    gzip: not code_reloading?,
    only: ShopMallWebWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ShopMallWebWeb.Router
end
