// このファイルは生成コード(pb.go)から復元したもの。以後はこれを正とし、
// 変更時は protoc で pb.go を再生成すること。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: payment-service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentMethodType int32

const (
	PaymentMethodType_PAYMENT_METHOD_TYPE_UNSPECIFIED PaymentMethodType = 0
	PaymentMethodType_CREDIT_CARD                     PaymentMethodType = 1
	PaymentMethodType_CASH_ON_DELIVERY                PaymentMethodType = 2
)

// Enum value maps for PaymentMethodType.
var (
	PaymentMethodType_name = map[int32]string{
		0: "PAYMENT_METHOD_TYPE_UNSPECIFIED",
		1: "CREDIT_CARD",
		2: "CASH_ON_DELIVERY",
	}
	PaymentMethodType_value = map[string]int32{
		"PAYMENT_METHOD_TYPE_UNSPECIFIED": 0,
		"CREDIT_CARD":                     1,
		"CASH_ON_DELIVERY":                2,
	}
)

func (x PaymentMethodType) Enum() *PaymentMethodType {
	p := new(PaymentMethodType)
	*p = x
	return p
}

func (x PaymentMethodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethodType) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_service_proto_enumTypes[0].Descriptor()
}

func (PaymentMethodType) Type() protoreflect.EnumType {
	return &file_payment_service_proto_enumTypes[0]
}

func (x PaymentMethodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethodType.Descriptor instead.
func (PaymentMethodType) EnumDescriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{0}
}

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING                    PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PROCESSING                 PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_REQUIRES_AUTHENTICATION    PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_SUCCEEDED                  PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_FAILED                     PaymentStatus = 5
	PaymentStatus_PAYMENT_STATUS_REFUNDING                  PaymentStatus = 6
	PaymentStatus_PAYMENT_STATUS_REFUNDED                   PaymentStatus = 7
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_PROCESSING",
		3: "PAYMENT_STATUS_REQUIRES_AUTHENTICATION",
		4: "PAYMENT_STATUS_SUCCEEDED",
		5: "PAYMENT_STATUS_FAILED",
		6: "PAYMENT_STATUS_REFUNDING",
		7: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":                    1,
		"PAYMENT_STATUS_PROCESSING":                 2,
		"PAYMENT_STATUS_REQUIRES_AUTHENTICATION":    3,
		"PAYMENT_STATUS_SUCCEEDED":                  4,
		"PAYMENT_STATUS_FAILED":                     5,
		"PAYMENT_STATUS_REFUNDING":                  6,
		"PAYMENT_STATUS_REFUNDED":                   7,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_service_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payment_service_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{1}
}

type RefundStatus int32

const (
	RefundStatus_REFUND_STATUS_REFUND_STATUS_UNSPECIFIED RefundStatus = 0
	RefundStatus_REFUND_STATUS_PENDING                   RefundStatus = 1
	RefundStatus_REFUND_STATUS_PROCESSING                RefundStatus = 2
	RefundStatus_REFUND_STATUS_SUCCEEDED                 RefundStatus = 3
	RefundStatus_REFUND_STATUS_FAILED                    RefundStatus = 4
)

// Enum value maps for RefundStatus.
var (
	RefundStatus_name = map[int32]string{
		0: "REFUND_STATUS_REFUND_STATUS_UNSPECIFIED",
		1: "REFUND_STATUS_PENDING",
		2: "REFUND_STATUS_PROCESSING",
		3: "REFUND_STATUS_SUCCEEDED",
		4: "REFUND_STATUS_FAILED",
	}
	RefundStatus_value = map[string]int32{
		"REFUND_STATUS_REFUND_STATUS_UNSPECIFIED": 0,
		"REFUND_STATUS_PENDING":                   1,
		"REFUND_STATUS_PROCESSING":                2,
		"REFUND_STATUS_SUCCEEDED":                 3,
		"REFUND_STATUS_FAILED":                    4,
	}
)

func (x RefundStatus) Enum() *RefundStatus {
	p := new(RefundStatus)
	*p = x
	return p
}

func (x RefundStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefundStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_service_proto_enumTypes[2].Descriptor()
}

func (RefundStatus) Type() protoreflect.EnumType {
	return &file_payment_service_proto_enumTypes[2]
}

func (x RefundStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefundStatus.Descriptor instead.
func (RefundStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{2}
}

type Payment struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId                string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentMethod          PaymentMethodType      `protobuf:"varint,3,opt,name=payment_method,json=paymentMethod,proto3,enum=payment_service.v1.PaymentMethodType" json:"payment_method,omitempty"`
	Amount                 string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency               string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status                 PaymentStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=payment_service.v1.PaymentStatus" json:"status,omitempty"`
	StripePaymentIntentId  string                 `protobuf:"bytes,7,opt,name=stripe_payment_intent_id,json=stripePaymentIntentId,proto3" json:"stripe_payment_intent_id,omitempty"`
	StripeClientSecret     string                 `protobuf:"bytes,8,opt,name=stripe_client_secret,json=stripeClientSecret,proto3" json:"stripe_client_secret,omitempty"`
	RequiresAuthentication bool                   `protobuf:"varint,9,opt,name=requires_authentication,json=requiresAuthentication,proto3" json:"requires_authentication,omitempty"`
	AuthenticationUrl      string                 `protobuf:"bytes,10,opt,name=authentication_url,json=authenticationUrl,proto3" json:"authentication_url,omitempty"`
	ErrorCode              string                 `protobuf:"bytes,11,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage           string                 `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CodFee                 string                 `protobuf:"bytes,13,opt,name=cod_fee,json=codFee,proto3" json:"cod_fee,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Payment) GetPaymentMethod() PaymentMethodType {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethodType_PAYMENT_METHOD_TYPE_UNSPECIFIED
}

func (x *Payment) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetStripePaymentIntentId() string {
	if x != nil {
		return x.StripePaymentIntentId
	}
	return ""
}

func (x *Payment) GetStripeClientSecret() string {
	if x != nil {
		return x.StripeClientSecret
	}
	return ""
}

func (x *Payment) GetRequiresAuthentication() bool {
	if x != nil {
		return x.RequiresAuthentication
	}
	return false
}

func (x *Payment) GetAuthenticationUrl() string {
	if x != nil {
		return x.AuthenticationUrl
	}
	return ""
}

func (x *Payment) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Payment) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Payment) GetCodFee() string {
	if x != nil {
		return x.CodFee
	}
	return ""
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Refund struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentId      string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId        string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount         string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Status         RefundStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=payment_service.v1.RefundStatus" json:"status,omitempty"`
	StripeRefundId string                 `protobuf:"bytes,7,opt,name=stripe_refund_id,json=stripeRefundId,proto3" json:"stripe_refund_id,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RefundedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=refunded_at,json=refundedAt,proto3" json:"refunded_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Refund) Reset() {
	*x = Refund{}
	mi := &file_payment_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refund) ProtoMessage() {}

func (x *Refund) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refund.ProtoReflect.Descriptor instead.
func (*Refund) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{1}
}

func (x *Refund) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Refund) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Refund) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Refund) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Refund) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Refund) GetStatus() RefundStatus {
	if x != nil {
		return x.Status
	}
	return RefundStatus_REFUND_STATUS_REFUND_STATUS_UNSPECIFIED
}

func (x *Refund) GetStripeRefundId() string {
	if x != nil {
		return x.StripeRefundId
	}
	return ""
}

func (x *Refund) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Refund) GetRefundedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefundedAt
	}
	return nil
}

func (x *Refund) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Refund) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type WebhookEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StripeEventId string                 `protobuf:"bytes,2,opt,name=stripe_event_id,json=stripeEventId,proto3" json:"stripe_event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Processed     bool                   `protobuf:"varint,5,opt,name=processed,proto3" json:"processed,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookEvent) Reset() {
	*x = WebhookEvent{}
	mi := &file_payment_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEvent) ProtoMessage() {}

func (x *WebhookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEvent.ProtoReflect.Descriptor instead.
func (*WebhookEvent) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{2}
}

func (x *WebhookEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebhookEvent) GetStripeEventId() string {
	if x != nil {
		return x.StripeEventId
	}
	return ""
}

func (x *WebhookEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WebhookEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *WebhookEvent) GetProcessed() bool {
	if x != nil {
		return x.Processed
	}
	return false
}

func (x *WebhookEvent) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *WebhookEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PaymentHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OldStatus     PaymentStatus          `protobuf:"varint,3,opt,name=old_status,json=oldStatus,proto3,enum=payment_service.v1.PaymentStatus" json:"old_status,omitempty"`
	NewStatus     PaymentStatus          `protobuf:"varint,4,opt,name=new_status,json=newStatus,proto3,enum=payment_service.v1.PaymentStatus" json:"new_status,omitempty"`
	ChangedBy     string                 `protobuf:"bytes,5,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"`
	ChangeReason  string                 `protobuf:"bytes,6,opt,name=change_reason,json=changeReason,proto3" json:"change_reason,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentHistory) Reset() {
	*x = PaymentHistory{}
	mi := &file_payment_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentHistory) ProtoMessage() {}

func (x *PaymentHistory) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentHistory.ProtoReflect.Descriptor instead.
func (*PaymentHistory) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentHistory) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentHistory) GetOldStatus() PaymentStatus {
	if x != nil {
		return x.OldStatus
	}
	return PaymentStatus_PAYMENT_STATUS_PAYMENT_STATUS_UNSPECIFIED
}

func (x *PaymentHistory) GetNewStatus() PaymentStatus {
	if x != nil {
		return x.NewStatus
	}
	return PaymentStatus_PAYMENT_STATUS_PAYMENT_STATUS_UNSPECIFIED
}

func (x *PaymentHistory) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *PaymentHistory) GetChangeReason() string {
	if x != nil {
		return x.ChangeReason
	}
	return ""
}

func (x *PaymentHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreatePaymentIntentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount          string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethodId string                 `protobuf:"bytes,4,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	CustomerId      string                 `protobuf:"bytes,5,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePaymentIntentRequest) Reset() {
	*x = CreatePaymentIntentRequest{}
	mi := &file_payment_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentRequest) ProtoMessage() {}

func (x *CreatePaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePaymentIntentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type ConfirmPaymentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentId       string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	PaymentIntentId string                 `protobuf:"bytes,2,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfirmPaymentRequest) Reset() {
	*x = ConfirmPaymentRequest{}
	mi := &file_payment_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentRequest) ProtoMessage() {}

func (x *ConfirmPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ConfirmPaymentRequest) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

type GetPaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusRequest) Reset() {
	*x = GetPaymentStatusRequest{}
	mi := &file_payment_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusRequest) ProtoMessage() {}

func (x *GetPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetPaymentStatusRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type CreateCODPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCODPaymentRequest) Reset() {
	*x = CreateCODPaymentRequest{}
	mi := &file_payment_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCODPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCODPaymentRequest) ProtoMessage() {}

func (x *CreateCODPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCODPaymentRequest.ProtoReflect.Descriptor instead.
func (*CreateCODPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCODPaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateCODPaymentRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type ConfirmCODPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmCODPaymentRequest) Reset() {
	*x = ConfirmCODPaymentRequest{}
	mi := &file_payment_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmCODPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmCODPaymentRequest) ProtoMessage() {}

func (x *ConfirmCODPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmCODPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmCODPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmCODPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ConfirmCODPaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CreateRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRefundRequest) Reset() {
	*x = CreateRefundRequest{}
	mi := &file_payment_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRefundRequest) ProtoMessage() {}

func (x *CreateRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRefundRequest.ProtoReflect.Descriptor instead.
func (*CreateRefundRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRefundRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreateRefundRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateRefundRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateRefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetRefundStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRefundStatusRequest) Reset() {
	*x = GetRefundStatusRequest{}
	mi := &file_payment_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRefundStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefundStatusRequest) ProtoMessage() {}

func (x *GetRefundStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefundStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRefundStatusRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetRefundStatusRequest) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

type ListPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ShopId        string                 `protobuf:"bytes,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	StatusFilter  []PaymentStatus        `protobuf:"varint,4,rep,packed,name=status_filter,json=statusFilter,proto3,enum=payment_service.v1.PaymentStatus" json:"status_filter,omitempty"`
	DateFrom      string                 `protobuf:"bytes,5,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,6,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	PaymentMethod PaymentMethodType      `protobuf:"varint,7,opt,name=payment_method,json=paymentMethod,proto3,enum=payment_service.v1.PaymentMethodType" json:"payment_method,omitempty"`
	Page          int32                  `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsRequest) Reset() {
	*x = ListPaymentsRequest{}
	mi := &file_payment_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsRequest) ProtoMessage() {}

func (x *ListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListPaymentsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ListPaymentsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListPaymentsRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *ListPaymentsRequest) GetStatusFilter() []PaymentStatus {
	if x != nil {
		return x.StatusFilter
	}
	return nil
}

func (x *ListPaymentsRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *ListPaymentsRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *ListPaymentsRequest) GetPaymentMethod() PaymentMethodType {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethodType_PAYMENT_METHOD_TYPE_UNSPECIFIED
}

func (x *ListPaymentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPaymentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetPaymentDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	RequesterRole string                 `protobuf:"bytes,3,opt,name=requester_role,json=requesterRole,proto3" json:"requester_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentDetailRequest) Reset() {
	*x = GetPaymentDetailRequest{}
	mi := &file_payment_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentDetailRequest) ProtoMessage() {}

func (x *GetPaymentDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentDetailRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentDetailRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetPaymentDetailRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *GetPaymentDetailRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *GetPaymentDetailRequest) GetRequesterRole() string {
	if x != nil {
		return x.RequesterRole
	}
	return ""
}

type HandleStripeWebhookRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StripeSignature string                 `protobuf:"bytes,1,opt,name=stripe_signature,json=stripeSignature,proto3" json:"stripe_signature,omitempty"`
	Payload         string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandleStripeWebhookRequest) Reset() {
	*x = HandleStripeWebhookRequest{}
	mi := &file_payment_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleStripeWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleStripeWebhookRequest) ProtoMessage() {}

func (x *HandleStripeWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleStripeWebhookRequest.ProtoReflect.Descriptor instead.
func (*HandleStripeWebhookRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{13}
}

func (x *HandleStripeWebhookRequest) GetStripeSignature() string {
	if x != nil {
		return x.StripeSignature
	}
	return ""
}

func (x *HandleStripeWebhookRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ProcessPaymentIntentSucceededRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentIntentId string                 `protobuf:"bytes,1,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	Amount          string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessPaymentIntentSucceededRequest) Reset() {
	*x = ProcessPaymentIntentSucceededRequest{}
	mi := &file_payment_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentIntentSucceededRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentIntentSucceededRequest) ProtoMessage() {}

func (x *ProcessPaymentIntentSucceededRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentIntentSucceededRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentIntentSucceededRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessPaymentIntentSucceededRequest) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *ProcessPaymentIntentSucceededRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type ProcessPaymentIntentFailedRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentIntentId string                 `protobuf:"bytes,1,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	ErrorCode       string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessPaymentIntentFailedRequest) Reset() {
	*x = ProcessPaymentIntentFailedRequest{}
	mi := &file_payment_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentIntentFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentIntentFailedRequest) ProtoMessage() {}

func (x *ProcessPaymentIntentFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentIntentFailedRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentIntentFailedRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{15}
}

func (x *ProcessPaymentIntentFailedRequest) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *ProcessPaymentIntentFailedRequest) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ProcessPaymentIntentFailedRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ProcessRefundCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRefundCompletedRequest) Reset() {
	*x = ProcessRefundCompletedRequest{}
	mi := &file_payment_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRefundCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRefundCompletedRequest) ProtoMessage() {}

func (x *ProcessRefundCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRefundCompletedRequest.ProtoReflect.Descriptor instead.
func (*ProcessRefundCompletedRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{16}
}

func (x *ProcessRefundCompletedRequest) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *ProcessRefundCompletedRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type CreatePaymentIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentIntentResponse) Reset() {
	*x = CreatePaymentIntentResponse{}
	mi := &file_payment_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentResponse) ProtoMessage() {}

func (x *CreatePaymentIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{17}
}

func (x *CreatePaymentIntentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreatePaymentIntentResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *CreatePaymentIntentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfirmPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=payment_service.v1.PaymentStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentResponse) Reset() {
	*x = ConfirmPaymentResponse{}
	mi := &file_payment_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentResponse) ProtoMessage() {}

func (x *ConfirmPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentResponse.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{18}
}

func (x *ConfirmPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmPaymentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_PAYMENT_STATUS_UNSPECIFIED
}

func (x *ConfirmPaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPaymentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PaymentStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=payment_service.v1.PaymentStatus" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusResponse) Reset() {
	*x = GetPaymentStatusResponse{}
	mi := &file_payment_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusResponse) ProtoMessage() {}

func (x *GetPaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetPaymentStatusResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_PAYMENT_STATUS_UNSPECIFIED
}

func (x *GetPaymentStatusResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type CreateCODPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCODPaymentResponse) Reset() {
	*x = CreateCODPaymentResponse{}
	mi := &file_payment_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCODPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCODPaymentResponse) ProtoMessage() {}

func (x *CreateCODPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCODPaymentResponse.ProtoReflect.Descriptor instead.
func (*CreateCODPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{20}
}

func (x *CreateCODPaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreateCODPaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfirmCODPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmCODPaymentResponse) Reset() {
	*x = ConfirmCODPaymentResponse{}
	mi := &file_payment_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmCODPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmCODPaymentResponse) ProtoMessage() {}

func (x *ConfirmCODPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmCODPaymentResponse.ProtoReflect.Descriptor instead.
func (*ConfirmCODPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{21}
}

func (x *ConfirmCODPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmCODPaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateRefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRefundResponse) Reset() {
	*x = CreateRefundResponse{}
	mi := &file_payment_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRefundResponse) ProtoMessage() {}

func (x *CreateRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRefundResponse.ProtoReflect.Descriptor instead.
func (*CreateRefundResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{22}
}

func (x *CreateRefundResponse) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *CreateRefundResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRefundStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        RefundStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=payment_service.v1.RefundStatus" json:"status,omitempty"`
	RefundAmount  int64                  `protobuf:"varint,2,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRefundStatusResponse) Reset() {
	*x = GetRefundStatusResponse{}
	mi := &file_payment_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRefundStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefundStatusResponse) ProtoMessage() {}

func (x *GetRefundStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefundStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRefundStatusResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetRefundStatusResponse) GetStatus() RefundStatus {
	if x != nil {
		return x.Status
	}
	return RefundStatus_REFUND_STATUS_REFUND_STATUS_UNSPECIFIED
}

func (x *GetRefundStatusResponse) GetRefundAmount() int64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

type ListPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsResponse) Reset() {
	*x = ListPaymentsResponse{}
	mi := &file_payment_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsResponse) ProtoMessage() {}

func (x *ListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{24}
}

func (x *ListPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *ListPaymentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetPaymentDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentDetailResponse) Reset() {
	*x = GetPaymentDetailResponse{}
	mi := &file_payment_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentDetailResponse) ProtoMessage() {}

func (x *GetPaymentDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentDetailResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentDetailResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{25}
}

func (x *GetPaymentDetailResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

var File_payment_service_proto protoreflect.FileDescriptor

const file_payment_service_proto_rawDesc = "" +
	"\n" +
	"\x15payment-service.proto\x12\x12payment_service.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x05\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12L\n" +
	"\x0epayment_method\x18\x03 \x01(\x0e2%.payment_service.v1.PaymentMethodTypeR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x129\n" +
	"\x06status\x18\x06 \x01(\x0e2!.payment_service.v1.PaymentStatusR\x06status\x127\n" +
	"\x18stripe_payment_intent_id\x18\a \x01(\tR\x15stripePaymentIntentId\x120\n" +
	"\x14stripe_client_secret\x18\b \x01(\tR\x12stripeClientSecret\x127\n" +
	"\x17requires_authentication\x18\t \x01(\bR\x16requiresAuthentication\x12-\n" +
	"\x12authentication_url\x18\n" +
	" \x01(\tR\x11authenticationUrl\x12\x1d\n" +
	"\n" +
	"error_code\x18\v \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\f \x01(\tR\ferrorMessage\x12\x17\n" +
	"\acod_fee\x18\r \x01(\tR\x06codFee\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbe\x03\n" +
	"\x06Refund\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x128\n" +
	"\x06status\x18\x06 \x01(\x0e2 .payment_service.v1.RefundStatusR\x06status\x12(\n" +
	"\x10stripe_refund_id\x18\a \x01(\tR\x0estripeRefundId\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12;\n" +
	"\vrefunded_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"refundedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x97\x02\n" +
	"\fWebhookEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fstripe_event_id\x18\x02 \x01(\tR\rstripeEventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12\x1c\n" +
	"\tprocessed\x18\x05 \x01(\bR\tprocessed\x12=\n" +
	"\fprocessed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc2\x02\n" +
	"\x0ePaymentHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12@\n" +
	"\n" +
	"old_status\x18\x03 \x01(\x0e2!.payment_service.v1.PaymentStatusR\toldStatus\x12@\n" +
	"\n" +
	"new_status\x18\x04 \x01(\x0e2!.payment_service.v1.PaymentStatusR\tnewStatus\x12\x1d\n" +
	"\n" +
	"changed_by\x18\x05 \x01(\tR\tchangedBy\x12#\n" +
	"\rchange_reason\x18\x06 \x01(\tR\fchangeReason\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb8\x01\n" +
	"\x1aCreatePaymentIntentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12*\n" +
	"\x11payment_method_id\x18\x04 \x01(\tR\x0fpaymentMethodId\x12\x1f\n" +
	"\vcustomer_id\x18\x05 \x01(\tR\n" +
	"customerId\"b\n" +
	"\x15ConfirmPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12*\n" +
	"\x11payment_intent_id\x18\x02 \x01(\tR\x0fpaymentIntentId\"8\n" +
	"\x17GetPaymentStatusRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"L\n" +
	"\x17CreateCODPaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"T\n" +
	"\x18ConfirmCODPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"\x7f\n" +
	"\x13CreateRefundRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"5\n" +
	"\x16GetRefundStatusRequest\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\"\xe7\x02\n" +
	"\x13ListPaymentsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x17\n" +
	"\ashop_id\x18\x03 \x01(\tR\x06shopId\x12F\n" +
	"\rstatus_filter\x18\x04 \x03(\x0e2!.payment_service.v1.PaymentStatusR\fstatusFilter\x12\x1b\n" +
	"\tdate_from\x18\x05 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x06 \x01(\tR\x06dateTo\x12L\n" +
	"\x0epayment_method\x18\a \x01(\x0e2%.payment_service.v1.PaymentMethodTypeR\rpaymentMethod\x12\x12\n" +
	"\x04page\x18\b \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\t \x01(\x05R\bpageSize\"\x82\x01\n" +
	"\x17GetPaymentDetailRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\x12%\n" +
	"\x0erequester_role\x18\x03 \x01(\tR\rrequesterRole\"a\n" +
	"\x1aHandleStripeWebhookRequest\x12)\n" +
	"\x10stripe_signature\x18\x01 \x01(\tR\x0fstripeSignature\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"j\n" +
	"$ProcessPaymentIntentSucceededRequest\x12*\n" +
	"\x11payment_intent_id\x18\x01 \x01(\tR\x0fpaymentIntentId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"\x93\x01\n" +
	"!ProcessPaymentIntentFailedRequest\x12*\n" +
	"\x11payment_intent_id\x18\x01 \x01(\tR\x0fpaymentIntentId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"T\n" +
	"\x1dProcessRefundCompletedRequest\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"{\n" +
	"\x1bCreatePaymentIntentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x87\x01\n" +
	"\x16ConfirmPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.payment_service.v1.PaymentStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"|\n" +
	"\x18GetPaymentStatusResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.payment_service.v1.PaymentStatusR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"S\n" +
	"\x18CreateCODPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x19ConfirmCODPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x14CreateRefundResponse\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"x\n" +
	"\x17GetRefundStatusResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .payment_service.v1.RefundStatusR\x06status\x12#\n" +
	"\rrefund_amount\x18\x02 \x01(\x03R\frefundAmount\"p\n" +
	"\x14ListPaymentsResponse\x127\n" +
	"\bpayments\x18\x01 \x03(\v2\x1b.payment_service.v1.PaymentR\bpayments\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"Q\n" +
	"\x18GetPaymentDetailResponse\x125\n" +
	"\apayment\x18\x01 \x01(\v2\x1b.payment_service.v1.PaymentR\apayment*_\n" +
	"\x11PaymentMethodType\x12#\n" +
	"\x1fPAYMENT_METHOD_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vCREDIT_CARD\x10\x01\x12\x14\n" +
	"\x10CASH_ON_DELIVERY\x10\x02*\x99\x02\n" +
	"\rPaymentStatus\x12-\n" +
	")PAYMENT_STATUS_PAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_STATUS_PROCESSING\x10\x02\x12*\n" +
	"&PAYMENT_STATUS_REQUIRES_AUTHENTICATION\x10\x03\x12\x1c\n" +
	"\x18PAYMENT_STATUS_SUCCEEDED\x10\x04\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x05\x12\x1c\n" +
	"\x18PAYMENT_STATUS_REFUNDING\x10\x06\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\a*\xab\x01\n" +
	"\fRefundStatus\x12+\n" +
	"'REFUND_STATUS_REFUND_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REFUND_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18REFUND_STATUS_PROCESSING\x10\x02\x12\x1b\n" +
	"\x17REFUND_STATUS_SUCCEEDED\x10\x03\x12\x18\n" +
	"\x14REFUND_STATUS_FAILED\x10\x042\xe2\a\n" +
	"\x0ePaymentService\x12v\n" +
	"\x13CreatePaymentIntent\x12..payment_service.v1.CreatePaymentIntentRequest\x1a/.payment_service.v1.CreatePaymentIntentResponse\x12g\n" +
	"\x0eConfirmPayment\x12).payment_service.v1.ConfirmPaymentRequest\x1a*.payment_service.v1.ConfirmPaymentResponse\x12m\n" +
	"\x10GetPaymentStatus\x12+.payment_service.v1.GetPaymentStatusRequest\x1a,.payment_service.v1.GetPaymentStatusResponse\x12m\n" +
	"\x10CreateCODPayment\x12+.payment_service.v1.CreateCODPaymentRequest\x1a,.payment_service.v1.CreateCODPaymentResponse\x12p\n" +
	"\x11ConfirmCODPayment\x12,.payment_service.v1.ConfirmCODPaymentRequest\x1a-.payment_service.v1.ConfirmCODPaymentResponse\x12a\n" +
	"\fCreateRefund\x12'.payment_service.v1.CreateRefundRequest\x1a(.payment_service.v1.CreateRefundResponse\x12j\n" +
	"\x0fGetRefundStatus\x12*.payment_service.v1.GetRefundStatusRequest\x1a+.payment_service.v1.GetRefundStatusResponse\x12a\n" +
	"\fListPayments\x12'.payment_service.v1.ListPaymentsRequest\x1a(.payment_service.v1.ListPaymentsResponse\x12m\n" +
	"\x10GetPaymentDetail\x12+.payment_service.v1.GetPaymentDetailRequest\x1a,.payment_service.v1.GetPaymentDetailResponseBTZRgithub.com/makoto-developer/go_microservice_example/microservices/payment/proto;v1b\x06proto3"

var (
	file_payment_service_proto_rawDescOnce sync.Once
	file_payment_service_proto_rawDescData []byte
)

func file_payment_service_proto_rawDescGZIP() []byte {
	file_payment_service_proto_rawDescOnce.Do(func() {
		file_payment_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_service_proto_rawDesc), len(file_payment_service_proto_rawDesc)))
	})
	return file_payment_service_proto_rawDescData
}

var file_payment_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_payment_service_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_payment_service_proto_goTypes = []any{
	(PaymentMethodType)(0),                       // 0: payment_service.v1.PaymentMethodType
	(PaymentStatus)(0),                           // 1: payment_service.v1.PaymentStatus
	(RefundStatus)(0),                            // 2: payment_service.v1.RefundStatus
	(*Payment)(nil),                              // 3: payment_service.v1.Payment
	(*Refund)(nil),                               // 4: payment_service.v1.Refund
	(*WebhookEvent)(nil),                         // 5: payment_service.v1.WebhookEvent
	(*PaymentHistory)(nil),                       // 6: payment_service.v1.PaymentHistory
	(*CreatePaymentIntentRequest)(nil),           // 7: payment_service.v1.CreatePaymentIntentRequest
	(*ConfirmPaymentRequest)(nil),                // 8: payment_service.v1.ConfirmPaymentRequest
	(*GetPaymentStatusRequest)(nil),              // 9: payment_service.v1.GetPaymentStatusRequest
	(*CreateCODPaymentRequest)(nil),              // 10: payment_service.v1.CreateCODPaymentRequest
	(*ConfirmCODPaymentRequest)(nil),             // 11: payment_service.v1.ConfirmCODPaymentRequest
	(*CreateRefundRequest)(nil),                  // 12: payment_service.v1.CreateRefundRequest
	(*GetRefundStatusRequest)(nil),               // 13: payment_service.v1.GetRefundStatusRequest
	(*ListPaymentsRequest)(nil),                  // 14: payment_service.v1.ListPaymentsRequest
	(*GetPaymentDetailRequest)(nil),              // 15: payment_service.v1.GetPaymentDetailRequest
	(*HandleStripeWebhookRequest)(nil),           // 16: payment_service.v1.HandleStripeWebhookRequest
	(*ProcessPaymentIntentSucceededRequest)(nil), // 17: payment_service.v1.ProcessPaymentIntentSucceededRequest
	(*ProcessPaymentIntentFailedRequest)(nil),    // 18: payment_service.v1.ProcessPaymentIntentFailedRequest
	(*ProcessRefundCompletedRequest)(nil),        // 19: payment_service.v1.ProcessRefundCompletedRequest
	(*CreatePaymentIntentResponse)(nil),          // 20: payment_service.v1.CreatePaymentIntentResponse
	(*ConfirmPaymentResponse)(nil),               // 21: payment_service.v1.ConfirmPaymentResponse
	(*GetPaymentStatusResponse)(nil),             // 22: payment_service.v1.GetPaymentStatusResponse
	(*CreateCODPaymentResponse)(nil),             // 23: payment_service.v1.CreateCODPaymentResponse
	(*ConfirmCODPaymentResponse)(nil),            // 24: payment_service.v1.ConfirmCODPaymentResponse
	(*CreateRefundResponse)(nil),                 // 25: payment_service.v1.CreateRefundResponse
	(*GetRefundStatusResponse)(nil),              // 26: payment_service.v1.GetRefundStatusResponse
	(*ListPaymentsResponse)(nil),                 // 27: payment_service.v1.ListPaymentsResponse
	(*GetPaymentDetailResponse)(nil),             // 28: payment_service.v1.GetPaymentDetailResponse
	(*timestamppb.Timestamp)(nil),                // 29: google.protobuf.Timestamp
}
var file_payment_service_proto_depIdxs = []int32{
	0,  // 0: payment_service.v1.Payment.payment_method:type_name -> payment_service.v1.PaymentMethodType
	1,  // 1: payment_service.v1.Payment.status:type_name -> payment_service.v1.PaymentStatus
	29, // 2: payment_service.v1.Payment.created_at:type_name -> google.protobuf.Timestamp
	29, // 3: payment_service.v1.Payment.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 4: payment_service.v1.Refund.status:type_name -> payment_service.v1.RefundStatus
	29, // 5: payment_service.v1.Refund.refunded_at:type_name -> google.protobuf.Timestamp
	29, // 6: payment_service.v1.Refund.created_at:type_name -> google.protobuf.Timestamp
	29, // 7: payment_service.v1.Refund.updated_at:type_name -> google.protobuf.Timestamp
	29, // 8: payment_service.v1.WebhookEvent.processed_at:type_name -> google.protobuf.Timestamp
	29, // 9: payment_service.v1.WebhookEvent.created_at:type_name -> google.protobuf.Timestamp
	1,  // 10: payment_service.v1.PaymentHistory.old_status:type_name -> payment_service.v1.PaymentStatus
	1,  // 11: payment_service.v1.PaymentHistory.new_status:type_name -> payment_service.v1.PaymentStatus
	29, // 12: payment_service.v1.PaymentHistory.created_at:type_name -> google.protobuf.Timestamp
	1,  // 13: payment_service.v1.ListPaymentsRequest.status_filter:type_name -> payment_service.v1.PaymentStatus
	0,  // 14: payment_service.v1.ListPaymentsRequest.payment_method:type_name -> payment_service.v1.PaymentMethodType
	1,  // 15: payment_service.v1.ConfirmPaymentResponse.status:type_name -> payment_service.v1.PaymentStatus
	1,  // 16: payment_service.v1.GetPaymentStatusResponse.status:type_name -> payment_service.v1.PaymentStatus
	2,  // 17: payment_service.v1.GetRefundStatusResponse.status:type_name -> payment_service.v1.RefundStatus
	3,  // 18: payment_service.v1.ListPaymentsResponse.payments:type_name -> payment_service.v1.Payment
	3,  // 19: payment_service.v1.GetPaymentDetailResponse.payment:type_name -> payment_service.v1.Payment
	7,  // 20: payment_service.v1.PaymentService.CreatePaymentIntent:input_type -> payment_service.v1.CreatePaymentIntentRequest
	8,  // 21: payment_service.v1.PaymentService.ConfirmPayment:input_type -> payment_service.v1.ConfirmPaymentRequest
	9,  // 22: payment_service.v1.PaymentService.GetPaymentStatus:input_type -> payment_service.v1.GetPaymentStatusRequest
	10, // 23: payment_service.v1.PaymentService.CreateCODPayment:input_type -> payment_service.v1.CreateCODPaymentRequest
	11, // 24: payment_service.v1.PaymentService.ConfirmCODPayment:input_type -> payment_service.v1.ConfirmCODPaymentRequest
	12, // 25: payment_service.v1.PaymentService.CreateRefund:input_type -> payment_service.v1.CreateRefundRequest
	13, // 26: payment_service.v1.PaymentService.GetRefundStatus:input_type -> payment_service.v1.GetRefundStatusRequest
	14, // 27: payment_service.v1.PaymentService.ListPayments:input_type -> payment_service.v1.ListPaymentsRequest
	15, // 28: payment_service.v1.PaymentService.GetPaymentDetail:input_type -> payment_service.v1.GetPaymentDetailRequest
	20, // 29: payment_service.v1.PaymentService.CreatePaymentIntent:output_type -> payment_service.v1.CreatePaymentIntentResponse
	21, // 30: payment_service.v1.PaymentService.ConfirmPayment:output_type -> payment_service.v1.ConfirmPaymentResponse
	22, // 31: payment_service.v1.PaymentService.GetPaymentStatus:output_type -> payment_service.v1.GetPaymentStatusResponse
	23, // 32: payment_service.v1.PaymentService.CreateCODPayment:output_type -> payment_service.v1.CreateCODPaymentResponse
	24, // 33: payment_service.v1.PaymentService.ConfirmCODPayment:output_type -> payment_service.v1.ConfirmCODPaymentResponse
	25, // 34: payment_service.v1.PaymentService.CreateRefund:output_type -> payment_service.v1.CreateRefundResponse
	26, // 35: payment_service.v1.PaymentService.GetRefundStatus:output_type -> payment_service.v1.GetRefundStatusResponse
	27, // 36: payment_service.v1.PaymentService.ListPayments:output_type -> payment_service.v1.ListPaymentsResponse
	28, // 37: payment_service.v1.PaymentService.GetPaymentDetail:output_type -> payment_service.v1.GetPaymentDetailResponse
	29, // [29:38] is the sub-list for method output_type
	20, // [20:29] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_payment_service_proto_init() }
func file_payment_service_proto_init() {
	if File_payment_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_proto_rawDesc), len(file_payment_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_service_proto_goTypes,
		DependencyIndexes: file_payment_service_proto_depIdxs,
		EnumInfos:         file_payment_service_proto_enumTypes,
		MessageInfos:      file_payment_service_proto_msgTypes,
	}.Build()
	File_payment_service_proto = out.File
	file_payment_service_proto_goTypes = nil
	file_payment_service_proto_depIdxs = nil
}
